Snapshot from coreutils-8.15.tar.xz

diff --git a/tests/du/move-dir-while-traversing b/tests/du/move-dir-while-traversing
--- a/tests/du/move-dir-while-traversing
+++ b/tests/du/move-dir-while-traversing
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Trigger a failed assertion in coreutils-8.9 and earlier.
 
-# Copyright (C) 2011 Free Software Foundation, Inc.
+# Copyright (C) 2011-2012 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -66,8 +66,8 @@ long=d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z
 # Five iterations was not enough in 2 of 7 "make -j20 check" runs on a
 # 6/12-core system.  However, using "10", I saw no failure in 20 trials.
 # Using 10 iterations was not enough, either.
-# Using 30, I saw no failure in 200 trials.
-for i in $(seq 30); do
+# Using 50, I saw no failure in 200 trials.
+for i in $(seq 50); do
   mkdir -p $t/3/a/b/c/$i/$long || framework_failure_
 done
 
@@ -91,6 +91,6 @@ test $? = 1 || fail=1
 # check for the new diagnostic
 printf "du: fts_read failed: $t/3/a/b: No such file or directory\n" > exp \
   || fail=1
-compare err exp || fail=1
+compare exp err || fail=1
 
 Exit $fail
diff --git a/tests/tail-2/pipe-f2 b/tests/tail-2/pipe-f2
--- a/tests/tail-2/pipe-f2
+++ b/tests/tail-2/pipe-f2
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Ensure that "tail -f fifo" tails indefinitely.
 
-# Copyright (C) 2009-2011 Free Software Foundation, Inc.
+# Copyright (C) 2009-2012 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -24,9 +24,20 @@ mkfifo_or_skip_ fifo
 echo 1 > fifo &
 echo 1 > exp || framework_failure_
 
-timeout 10 tail -f fifo > out
-test $? = 124 || fail=1
+timeout 10 tail -f fifo > out & pid=$!
 
-compare out exp || fail=1
+check_tail_output()
+{
+  local n_sec="$1"
+  test -s out || { sleep $n_sec; return 1; }
+}
+
+# Wait 6.3s for tail to write something.
+retry_delay_ check_tail_output .1 7 || fail=1
+
+compare exp out || fail=1
+
+# Kill the still-running tail, or fail if it's gone.
+kill $pid || fail=1
 
 Exit $fail
