Snapshot from coreutils-6.3.tar.bz2

diff --git a/Makefile.maint b/Makefile.maint
--- a/Makefile.maint
+++ b/Makefile.maint
@@ -24,11 +24,18 @@
 ME := Makefile.maint
 
 # Do not save the original name or timestamp in the .tar.gz file.
-GZIP_ENV = '--no-name --best --rsyncable'
+# Use --rsyncable if available.
+gzip_rsyncable := \
+  $(shell gzip --help 2>/dev/null|grep rsyncable >/dev/null && echo --rsyncable)
+GZIP_ENV = '--no-name --best $(gzip_rsyncable)'
 
 CVS = cvs
 
-CVS_LIST = cvsu --find --types=AFGM
+# cvsu is part of the cvsutils package: http://www.red-bean.com/cvsutils/
+CVS_LIST = build-aux/vc-list-files
+
+CVS_LIST_EXCEPT = \
+  $(CVS_LIST) | if test -f .x-$@; then grep -vEf .x-$@; else grep -v ChangeLog; fi
 
 ifeq ($(origin prev_version_file), undefined)
   prev_version_file = .prev-version
@@ -56,125 +63,122 @@ export LC_ALL = C
 ## Sanity checks.  ##
 ## --------------- ##
 
+# FIXME: add a check to prohibit definition in src/*.c of symbols defined
+# in system.h.  E.g. today I removed from tail.c a useless definition of
+# ENOSYS.  It was useless because system.h ensures it's defined.
+
 # Checks that don't require cvs.
 # Run `changelog-check' last, as previous test may reveal problems requiring
 # new ChangeLog entries.
 local-checks-available = \
   po-check copyright-check writable-files m4-check author_mark_check \
-  changelog-check strftime-check syntax-check makefile_path_separator_check \
-  makefile-check
+  changelog-check patch-check strftime-check $(syntax-check-rules) \
+  makefile_path_separator_check \
+  makefile-check check-AUTHORS
 .PHONY: $(local-checks-available)
 
 local-check = $(filter-out $(local-checks-to-skip), $(local-checks-available))
 
+# Collect the names of rules starting with `sc_'.
+syntax-check-rules := $(shell sed -n 's/^\(sc_[a-zA-Z0-9_-]*\):.*/\1/p' $(ME))
 .PHONY: $(syntax-check-rules)
-syntax-check-rules = \
-  sc_cast_of_argument_to_free \
-  sc_cast_of_x_alloc_return_value \
-  sc_cast_of_alloca_return_value \
-  sc_dd_max_sym_length \
-  sc_error_exit_success \
-  sc_file_system \
-  sc_no_if_have_config_h \
-  sc_obsolete_symbols \
-  sc_prohibit_atoi_atof \
-  sc_prohibit_jm_in_m4 \
-  sc_root_tests \
-  sc_space_tab \
-  sc_sun_os_names \
-  sc_system_h_headers \
-  sc_tight_scope \
-  sc_trailing_blank \
-  sc_unmarked_diagnostics \
-  sc_useless_cpp_parens
 
 syntax-check: $(syntax-check-rules)
-#	@grep -E '#  *include <(limits|std(def|arg|bool))\.h>'		\
+#	@grep -nE '#  *include <(limits|std(def|arg|bool))\.h>'		\
 #	    $$(find -type f -name '*.[chly]') &&			\
 #	  { echo '$(ME): found conditional include' 1>&2;		\
 #	    exit 1; } || :
 
-#	grep -E '^#  *include <(string|stdlib)\.h>'			\
+#	grep -nE '^#  *include <(string|stdlib)\.h>'			\
 #	    $(srcdir)/{lib,src}/*.[chy] &&				\
 #	  { echo '$(ME): FIXME' 1>&2;					\
 #	    exit 1; } || :
 # FIXME: don't allow `#include .strings\.h' anywhere
 
-# FIXME: add a check for this.
-# Nearly every lib/*.c file must include config.h, like this:
-#  #ifdef HAVE_CONFIG_H
-#  # include <config.h>
-#  #endif
-
 sc_cast_of_argument_to_free:
-	@grep -E '\<free \(\(' $(srcdir)/{lib,src}/*.[chly] &&		\
+	@grep -nE '\<free \(\(' $(srcdir)/{lib,src}/*.[chly] &&		\
 	  { echo '$(ME): don'\''t cast free argument' 1>&2;		\
 	    exit 1; } || :
 
 sc_cast_of_x_alloc_return_value:
-	@grep -E --exclude=$(srcdir)/lib/regex.c			\
+	@grep -nE --exclude=$(srcdir)/lib/regex.c			\
 	    '\*\) *x(m|c|re)alloc\>'					\
 	    $(srcdir)/{lib,src}/*.[chy] &&				\
 	  { echo '$(ME): don'\''t cast x*alloc return value' 1>&2;	\
 	    exit 1; } || :
 
 sc_cast_of_alloca_return_value:
-	@grep -E '\*\) *alloca\>'					\
+	@grep -nE '\*\) *alloca\>'					\
 	    $(srcdir)/src/*.[chy] &&					\
 	  { echo '$(ME): don'\''t cast alloca return value' 1>&2;	\
 	    exit 1; } || :
 
 sc_space_tab:
-	@( $(CVS_LIST) ) > /dev/null 2>&1 || : &&			\
-	  grep '[ ]	'						\
-	     $$($(CVS_LIST) | grep -vEf .x-$@ ) &&			\
+	@grep -n '[ ]	' $$($(CVS_LIST_EXCEPT)) &&			\
 	  { echo '$(ME): found SPACE-TAB sequence; remove the SPACE'	\
 		1>&2; exit 1; } || :
 
-# Don't use atoi, atof, atol, atoll, or atoq in `real' code.
+# Don't use the old ato* functions in `real' code.
 # They provide no error checking mechanism.
 # Instead, use strto* functions.
 sc_prohibit_atoi_atof:
-	@( $(CVS_LIST) ) > /dev/null 2>&1 || : &&			\
-	  grep -E '\<(ato[filq]|atoll)\>'				\
-	     $$($(CVS_LIST) | grep -vEf .x-$@ ) &&			\
-	  { echo '$(ME): do not use atof, atoi, atol, atoll, or atoq'	\
+	@grep -nE '\<ato([filq]|ll)\>' $$($(CVS_LIST_EXCEPT)) &&	\
+	  { echo '$(ME): do not use ato''f, ato''i, ato''l, ato''ll, or ato''q'	\
 		1>&2; exit 1; } || :
 
 # Using EXIT_SUCCESS as the first argument to error is misleading,
 # since when that parameter is 0, error does not exit.  Use `0' instead.
 sc_error_exit_success:
-	@grep -F 'error (EXIT_SUCCESS,'					\
+	@grep -nF 'error (EXIT_SUCCESS,'					\
 	    $$(find -type f -name '*.[chly]') &&			\
 	  { echo '$(ME): found error (EXIT_SUCCESS' 1>&2;		\
 	    exit 1; } || :
 
 sc_file_system:
-	@grep -i 'filesystem'						\
-	     $$($(CVS_LIST) | grep -vEf .x-$@ ) &&			\
-	  { echo '$(ME): found use of "filesystem";'			\
+	@grep -ni 'file''system' $$($(CVS_LIST_EXCEPT)) &&		\
+	  { echo '$(ME): found use of "file''system";'			\
 	    'rewrite to use "file system"' 1>&2;			\
 	    exit 1; } || :
 
-sc_no_if_have_config_h:
-	@( $(CVS_LIST) ) > /dev/null 2>&1 || : &&			\
-	  grep '^# *if HAVE_CONFIG_H'					\
-	     $$($(CVS_LIST) | grep -vEf .x-$@ ) &&			\
-	  { echo '$(ME): found use of #if HAVE_CONFIG_H; use #ifdef'	\
+sc_no_have_config_h:
+	@grep -n 'HAVE''_CONFIG_H' $$($(CVS_LIST_EXCEPT)) &&		\
+	  { echo '$(ME): found use of HAVE''_CONFIG_H; remove'		\
 		1>&2; exit 1; } || :
 
+# Nearly all .c files must include <config.h>.
+sc_require_config_h:
+	@if $(CVS_LIST_EXCEPT) | grep '\.c$$' > /dev/null; then		\
+	  grep -L '^# *include <config\.h>'				\
+		$$($(CVS_LIST_EXCEPT) | grep '\.c$$')			\
+	      | grep . &&						\
+	  { echo '$(ME): the above files do not include <config.h>'	\
+		1>&2; exit 1; } || :;					\
+	else :;								\
+	fi
+
+# Prohibit the inclusion of assert.h without an actual use of assert.
+sc_prohibit_assert_without_use:
+	@if $(CVS_LIST_EXCEPT) | grep '\.c$$' > /dev/null; then		\
+	  files=$$(grep -l '# *include <assert\.h>'			\
+		    $$($(CVS_LIST_EXCEPT) | grep '\.c$$')) &&		\
+	  grep -L '\<assert (' $$files					\
+	      | grep . &&						\
+	    { echo "$(ME): the above files include <assert.h> but don't use it" \
+		  1>&2; exit 1; } || :;					\
+	else :;								\
+	fi
+
 sc_obsolete_symbols:
-	@( $(CVS_LIST) ) > /dev/null 2>&1 || : &&			\
-	  grep -E '\<(HAVE_FCNTL_H)\>'					\
-	     $$($(CVS_LIST) | grep -vEf .x-$@ ) &&			\
-	  { echo '$(ME): do not use HAVE_FCNTL_H'			\
+	@grep -nE '\<(HAVE''_FCNTL_H|O''_NDELAY)\>'			\
+	     $$($(CVS_LIST_EXCEPT)) &&					\
+	  { echo '$(ME): do not use HAVE''_FCNTL_H or O''_NDELAY'	\
 		1>&2; exit 1; } || :
 
 # FIXME: warn about definitions of EXIT_FAILURE, EXIT_SUCCESS, STREQ
 
 # Each nonempty line must start with a year number, or a TAB.
 sc_changelog:
-	@grep '^[^12	]' $$(find . -maxdepth 2 -name ChangeLog) &&	\
+	@grep -n '^[^12	]' $$(find . -maxdepth 2 -name ChangeLog) &&	\
 	  { echo '$(ME): found unexpected prefix in a ChangeLog' 1>&2;	\
 	    exit 1; } || :
 
@@ -182,31 +186,31 @@ sc_changelog:
 # with the strings from the two affected variables.
 dd_c = $(srcdir)/src/dd.c
 sc_dd_max_sym_length:
-	@test -f $(dd_c) || exit 0;				\
-	len=$$( (sed -n '/conversions\[\] =$$/,/^};/p' $(dd_c);	\
+ifneq ($(wildcard $(dd_c)),)
+	@len=$$( (sed -n '/conversions\[\] =$$/,/^};/p' $(dd_c);\
 		 sed -n '/flags\[\] =$$/,/^};/p' $(dd_c) )	\
 		|sed -n '/"/s/^[^"]*"\([^"]*\)".*/\1/p'		\
-              | wc --max-line-length);				\
+	      | wc --max-line-length);				\
 	max=$$(sed -n '/^#define LONGEST_SYMBOL /s///p' $(dd_c)	\
 	      |tr -d '"' | wc --max-line-length);		\
 	if test "$$len" = "$$max"; then :; else			\
 	  echo 'dd.c: LONGEST_SYMBOL is not longest' 1>&2;	\
 	  exit 1;						\
 	fi
+endif
 
 # Many m4 macros names once began with `jm_'.
 # On 2004-04-13, they were all changed to start with gl_ instead.
 # Make sure that none are inadvertently reintroduced.
 sc_prohibit_jm_in_m4:
-	@( $(CVS_LIST) ) > /dev/null 2>&1 || : &&			\
-	  grep -E 'jm_[A-Z]'						\
-		$$($(CVS_LIST) $(srcdir)/m4 |grep '\.m4$$') &&		\
-	    { echo '$(ME): do not use jm_ in m4 macro names'		\
+	@grep -nE 'jm_[A-Z]'					\
+		$$($(CVS_LIST) m4 |grep '\.m4$$'; echo /dev/null) && \
+	    { echo '$(ME): do not use jm_ in m4 macro names'	\
 	      1>&2; exit 1; } || :
 
 sc_root_tests:
 	@t1=sc-root.expected; t2=sc-root.actual;			\
-	grep -l '^PRIV_CHECK_ARG=require-root'				\
+	grep -nl '^PRIV_CHECK_ARG=require-root'				\
 	  $$($(CVS_LIST) tests) |sed s,tests,., |sort > $$t1;		\
 	sed -n 's,	cd \([^ ]*\) .*MAKE..check TESTS=\(.*\),./\1/\2,p' \
 	  $(srcdir)/tests/Makefile.am |sort > $$t2;			\
@@ -229,51 +233,71 @@ sc_root_tests:
 # the headers already included via system.h.
 sc_system_h_headers: .re-list
 	@if test -f $(srcdir)/src/system.h; then			\
-	  ( $(CVS_LIST) ) > /dev/null 2>&1 || exit 0;			\
 	  trap 'rc=$$?; rm -f .re-list; exit $$rc' 0 1 2 3 15;		\
-	  grep -E -f .re-list						\
-	      $$($(CVS_LIST) src | grep -Ev '(copy|system)\.h$$')	\
+	  grep -nE -f .re-list						\
+	      $$($(CVS_LIST) src |					\
+		 grep -Ev '((copy|system)\.h|parse-gram\.c)$$')		\
 	    && { echo '$(ME): the above are already included via system.h'\
 		  1>&2;  exit 1; } || :;				\
 	fi
 
 sc_sun_os_names:
-	@( $(CVS_LIST) ) > /dev/null 2>&1 || : && \
-	grep -Ei \
+	@grep -nEi \
 	    'solaris[^[:alnum:]]*2\.(7|8|9|[1-9][0-9])|sunos[^[:alnum:]][6-9]' \
-	  $$($(CVS_LIST) | grep -vEf .x-$@ ) &&				\
+	    $$($(CVS_LIST_EXCEPT)) &&					\
 	  { echo '$(ME): found misuse of Sun OS version numbers' 1>&2;	\
+	    exit 1; } || :
+
+sc_the_the:
+	@grep -ni '\<the ''the\>' $$($(CVS_LIST_EXCEPT)) &&		\
+	  { echo '$(ME): found use of "the ''the";' 1>&2;		\
 	    exit 1; } || :
 
 sc_tight_scope:
 	$(MAKE) -C src $@
 
 sc_trailing_blank:
-	@( $(CVS_LIST) ) > /dev/null 2>&1 || : &&			\
-	  grep '[	 ]$$'						\
-	     $$($(CVS_LIST) | grep -vEf .x-$@ ) &&			\
+	@grep -n '[	 ]$$' $$($(CVS_LIST_EXCEPT)) &&			\
 	  { echo '$(ME): found trailing blank(s)'			\
+		1>&2; exit 1; } || :
+
+# Match lines like the following, but where there is only one space
+# between the options and the description:
+#   -D, --all-repeated[=delimit-method]  print all duplicate lines\n
+longopt_re = --[a-z][0-9A-Za-z-]*(\[=[0-9A-Za-z-]*\])?
+sc_two_space_separator_in_usage:
+	@grep -nE '^   *(-[A-Za-z],)? $(longopt_re) [^ ].*\\$$'		\
+	    $$($(CVS_LIST_EXCEPT)) &&					\
+	  { echo "$(ME): help2man requires at least two spaces between"; \
+	    echo "$(ME): an option and its description"; \
 		1>&2; exit 1; } || :
 
 # Look for diagnostics that aren't marked for translation.
 # This won't find any for which error's format string is on a separate line.
 sc_unmarked_diagnostics:
-	@( $(CVS_LIST) ) > /dev/null 2>&1 || : &&			\
-	  grep -E							\
-	    '\<error \([^"]*"[^"]*[a-z]{3}'				\
-	     $$($(CVS_LIST) | grep -vEf .x-$@ )				\
-	  | grep -v '_(' &&						\
+	@grep -nE							\
+	    '\<error \([^"]*"[^"]*[a-z]{3}' $$($(CVS_LIST_EXCEPT))	\
+	  | grep -v '_''(' &&						\
 	  { echo '$(ME): found unmarked diagnostic(s)' 1>&2;		\
 	    exit 1; } || :
 
 # Avoid useless parentheses like those in this example:
 # #if defined (SYMBOL) || defined (SYM2)
 sc_useless_cpp_parens:
-	@( $(CVS_LIST) ) > /dev/null 2>&1 || : &&			\
-	  grep '^# *if .*defined *('					\
-	     $$($(CVS_LIST) | grep -vEf .x-$@ ) &&			\
+	@grep -n '^# *if .*defined *(' $$($(CVS_LIST_EXCEPT)) &&	\
 	  { echo '$(ME): found useless parentheses in cpp directive'	\
 		1>&2; exit 1; } || :
+
+# Ensure that the c99-to-c89 patch applies cleanly.
+patch-check:
+	rm -rf src-c89 $@.1 $@.2
+	cp -a src src-c89
+	(cd src-c89; patch -V never --fuzz=0) < src/c99-to-c89.diff \
+	  > $@.1 2>&1
+	grep -v '^patching file ' $@.1 > $@.2 || :
+	fail=0; test -s $@.2 && fail=1 || : ; \
+	rm -rf src-c89 $@.1 $@.2; \
+	test $$fail = 0
 
 # Ensure that date's --help output stays in sync with the info
 # documentation for GNU strftime.  The only exception is %N,
@@ -290,11 +314,14 @@ strftime-check:
 	  rm -f $@-src $@-info;						\
 	fi
 
+check-AUTHORS:
+	$(MAKE) -C src $@
+
 # Ensure that we use only the standard $(VAR) notation,
 # not @...@ in Makefile.am, now that we can rely on automake
 # to emit a definition for each substituted variable.
 makefile-check:
-	grep -E '@[A-Z_0-9]+@' `find . -name Makefile.am` \
+	grep -nE '@[A-Z_0-9]+@' `find . -name Makefile.am` \
 	  && { echo 'Makefile.maint: use $$(...), not @...@' 1>&2; exit 1; } || :
 
 news-date-check: NEWS
@@ -317,19 +344,21 @@ changelog-check:
 	fi
 
 m4-check:
-	@grep 'AC_DEFUN([^[]' m4/*.m4 \
+	@grep -n 'AC_DEFUN([^[]' m4/*.m4 \
 	  && { echo 'Makefile.maint: quote the first arg to AC_DEFUN' 1>&2; \
 	       exit 1; } || :
 
 # Verify that all source files using _() are listed in po/POTFILES.in.
-# FIXME: don't hard-code src/false.c below; use a more general mechanism.
+# FIXME: don't hard-code file names below; use a more general mechanism.
 po-check:
-	( $(CVS_LIST) ) > /dev/null 2>&1 || : &&			\
 	if test -f po/POTFILES.in; then					\
 	  grep -E -v '^(#|$$)' po/POTFILES.in				\
 	    | grep -v '^src/false\.c$$' | sort > $@-1;			\
 	  files=;							\
-	  for file in $$($(CVS_LIST) lib src | grep '\.[chly]$$'); do	\
+	  for file in $$($(CVS_LIST_EXCEPT)) lib/*.[ch]; do		\
+	    case $$file in						\
+	    djgpp/* | man/*) continue;;					\
+	    esac;							\
 	    case $$file in						\
 	    *.[ch])							\
 	      base=`expr " $$file" : ' \(.*\)\..'`;			\
@@ -337,7 +366,7 @@ po-check:
 	    esac;							\
 	    files="$$files $$file";					\
 	  done;								\
-	  grep -E -l '\bN?_\([^)"]*("|$$)' $$files | sort > $@-2;	\
+	  grep -E -l '\bN?_\([^)"]*("|$$)' $$files | sort -u > $@-2;	\
 	  diff -u $@-1 $@-2 || exit 1;					\
 	  rm -f $@-1 $@-2;						\
 	fi
@@ -346,7 +375,7 @@ po-check:
 # the English word `and', the string must be marked with `N_ (...)' so that
 # gettext recognizes it as a string requiring translation.
 author_mark_check:
-	@grep '^# *define AUTHORS "[^"]* and ' src/*.c |grep -v ' N_ (' && \
+	@grep -n '^# *define AUTHORS "[^"]* and ' src/*.c |grep -v ' N_ (' && \
 	  { echo 'Makefile.maint: enclose the above strings in N_ (...)' 1>&2; \
 	    exit 1; } || :
 
@@ -358,7 +387,7 @@ author_mark_check:
 # that we'd have to worry about limits on command line length.
 msg = 'Makefile.maint: Do not use `:'\'' above; use @PATH_SEPARATOR@ instead'
 makefile_path_separator_check:
-	@grep 'PATH=.*:' `find $(srcdir) -name Makefile.am` \
+	@grep -n 'PATH=.*:' `find $(srcdir) -name Makefile.am` \
 	  && { echo $(msg) 1>&2; exit 1; } || :
 
 # Check that `make alpha' will not fail at the end of the process.
@@ -405,7 +434,7 @@ cvs-diff-check:
 
 cvs-check: cvs-diff-check cvs-tag-check
 
-maintainer-distcheck: changelog-check
+maintainer-distcheck:
 	$(MAKE) distcheck
 	$(MAKE) my-distcheck
 
@@ -430,7 +459,8 @@ null_AM_MAKEFLAGS = \
 # Detect format-string/arg-list mismatches that would normally be obscured
 # by the use of _().  The --disable-nls effectively defines away that macro,
 # and building with CFLAGS='-Wformat -Werror' causes any format warning to be
-# treated as a failure.  Also, check for shadowing problems with -Wshadow.
+# treated as a failure.  Also, check for shadowing problems with -Wshadow,
+# and for pointer arithmetic problems with -Wpointer-arith.
 # These CFLAGS are pretty strict.  If you build this target, you probably
 # have to have a recent version of gcc and glibc headers.
 TMPDIR ?= /tmp
@@ -441,7 +471,7 @@ my-distcheck: $(local-check) $(release_archive_dir)/$(prev-tgz)
 	GZIP=$(GZIP_ENV) $(AMTAR) -C $(t) -zxf $(distdir).tar.gz
 	cd $(t)/$(distdir)				\
 	  && ./configure --disable-nls			\
-	  && $(MAKE) CFLAGS='-Werror -Wall -Wformat -Wshadow' \
+	  && $(MAKE) CFLAGS='-Werror -Wall -Wformat -Wshadow -Wpointer-arith' \
 	      AM_MAKEFLAGS='$(null_AM_MAKEFLAGS)'	\
 	  && $(MAKE) dvi				\
 	  && $(MAKE) check				\
@@ -456,16 +486,6 @@ my-distcheck: $(local-check) $(release_archive_dir)/$(prev-tgz)
 
 WGET = wget
 WGETFLAGS = -C off
-
-tgz-md5 = $(shell md5sum < $(my_distdir).tar.gz|sed 's/  -//')
-tgz-sha1 = $(shell sha1sum < $(my_distdir).tar.gz|sed 's/  -//')
-bz2-md5 = $(shell md5sum < $(my_distdir).tar.bz2|sed 's/  -//')
-bz2-sha1 = $(shell sha1sum < $(my_distdir).tar.bz2|sed 's/  -//')
-xdelta-md5 = $(shell md5sum < $(xd-delta)|sed 's/  -//')
-xdelta-sha1 = $(shell sha1sum < $(xd-delta)|sed 's/  -//')
-tgz-size = $(shell du --human $(my_distdir).tar.gz|sed 's/\([MkK]\).*/ \1B/')
-bz2-size = $(shell du --human $(my_distdir).tar.bz2|sed 's/\([MkK]\).*/ \1B/')
-xd-size = $(shell du --human $(xd-delta)|sed 's/\([MkK]\).*/ \1B/')
 
 rel-check:
 	tarz=/tmp/rel-check-tarz-$$$$; \
@@ -508,30 +528,9 @@ move_if_change ?= move-if-change
 # --------------------- #
 
 .PHONY: update
-local_updates ?= wget-update cvs-update po-update
+local_updates ?= wget-update cvs-update
 update: $(local_updates)
 
-
-# ------------------- #
-# Updating PO files.  #
-# ------------------- #
-
-po_repo = http://www.iro.umontreal.ca/contrib/po/maint/$(PACKAGE)
-.PHONY: do-po-update po-update
-do-po-update:
-	tmppo=/tmp/$(PACKAGE)-$(VERSION)-po &&\
-	rm -rf $$tmppo && \
-	mkdir $$tmppo && \
-	(cd $$tmppo && \
-	  $(WGET) $(WGETFLAGS) -r -l1 -nd --no-parent -A '*.po' $(po_repo)) &&\
-	cp $$tmppo/*.po po
-	cd po && $(MAKE) update-po
-	$(MAKE) po-check
-
-po-update:
-	if test -d "po"; then \
-	  $(MAKE) do-po-update; \
-	fi
 
 # -------------------------- #
 # Updating GNU build tools.  #
@@ -594,7 +593,7 @@ cvs-update:
 emit_upload_commands:
 	@echo =====================================
 	@echo =====================================
-	@echo "$(srcdir)/gnupload $(GNUPLOADFLAGS) \\"
+	@echo "$(srcdir)/build-aux/gnupload $(GNUPLOADFLAGS) \\"
 	@echo "    --to $(gnu_rel_host):coreutils \\"
 	@echo "  $(rel-files)"
 	@echo '# send the /tmp/announcement e-mail'
@@ -605,9 +604,11 @@ $(xd-delta): $(release_archive_dir)/$(prev-tgz) $(distdir).tar.gz
 	xdelta delta -9 $^ $@ || :
 
 .PHONY: alpha beta major
-alpha beta major: news-date-check $(local-check)
-	test $@ = major && case $(VERSION) in *-cvs*) \
-	  echo "invalid version string: $(VERSION)" 1>&2; exit 1;; esac
+alpha beta major: news-date-check changelog-check $(local-check)
+	test $@ = major						\
+	  && { echo $(VERSION) | grep -E '^[0-9]+(\.[0-9]+)+$$'	\
+	       || { echo "invalid version string: $(VERSION)" 1>&2; exit 1;};}\
+	  || :
 	$(MAKE) cvs-dist
 	$(MAKE) $(xd-delta)
 	$(MAKE) -s announcement RELEASE_TYPE=$@ > /tmp/announce-$(my_distdir)
diff --git a/tests/chgrp/basic b/tests/chgrp/basic
--- a/tests/chgrp/basic
+++ b/tests/chgrp/basic
@@ -1,6 +1,24 @@
 #!/bin/sh
 # make sure chgrp is reasonable
 
+# Copyright (C) 2000, 2001, 2003, 2004, 2005, 2006 Free Software
+# Foundation, Inc.
+
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
+# 02110-1301, USA.
+
 if test "$VERBOSE" = yes; then
   set -x
   chgrp --version
@@ -36,90 +54,72 @@ chgrp $g2 f || fail=1
 chgrp $g2 f2 || fail=1
 chgrp -R $g1 d || fail=1
 
-# Don't let verbose output interfere.
-test "$VERBOSE" = yes && set +x
+d_files='d d/f3'
 
-(
-  chgrp -c $g1 f
-  chgrp -c $g2 f
-  chgrp -c $g2 f
-  chgrp --verbose '' f
-  chgrp --verbose $g1 f
-  chgrp --verbose $g1 f
-  chgrp --verbose --reference=f2 f
-  chgrp -R --verbose $g2 d
-  chgrp -R --verbose $g1 d
-  chgrp -R -c $g2 d
-  chgrp -R -c $g1 d
-  chgrp -c $g2 d
+chgrp $g1 f || fail=1  ; test `stat --p=%g f` = $g1 || fail=1
+chgrp $g2 f || fail=1  ; test `stat --p=%g f` = $g2 || fail=1
+chgrp $g2 f || fail=1  ; test `stat --p=%g f` = $g2 || fail=1
+chgrp '' f  || fail=1  ; test `stat --p=%g f` = $g2 || fail=1
+chgrp $g1 f || fail=1  ; test `stat --p=%g f` = $g1 || fail=1
+chgrp $g1 f || fail=1  ; test `stat --p=%g f` = $g1 || fail=1
+chgrp --reference=f2 f ; test `stat --p=%g f` = $g2 || fail=1
 
-  rm -f f
-  touch f
-  ln -s f symlink
-  chgrp $g1 f
-  chgrp -h $g2 symlink
+chgrp -R $g2 d ||fail=1; test `stat --p=%g: $d_files` = "$g2:$g2:" || fail=1
+chgrp -R $g1 d ||fail=1; test `stat --p=%g: $d_files` = "$g1:$g1:" || fail=1
+chgrp -R $g2 d ||fail=1; test `stat --p=%g: $d_files` = "$g2:$g2:" || fail=1
+chgrp -R $g1 d ||fail=1; test `stat --p=%g: $d_files` = "$g1:$g1:" || fail=1
+chgrp $g2 d    ||fail=1; test `stat --p=%g: $d_files` = "$g2:$g1:" || fail=1
 
-  # This should not change the group of f.
-  chgrp -h -c $g2 symlink
-  chown --from=:$g1 -c :$g2 f
+rm -f f
+touch f
+ln -s f symlink
+chgrp $g1 f
+test `stat --printf=%g f` = $g1 || fail=1
 
-  # This *should* change the group of f.
-  # Though note that the diagnostic is misleading in that
-  # it says the `group of `symlink'' has been changed.
-  chgrp -c $g1 symlink
-  chown --from=:$g1 -c :$g2 f
+# This should not change the group of f.
+chgrp -h $g2 symlink
+test `stat --printf=%g f` = $g1 || fail=1
+test `stat --printf=%g symlink` = $g2 || fail=1
 
-  # If -R is specified without -H or L, -h is assumed.
-  chgrp -h $g1 f symlink
-  chgrp -R $g2 symlink
-  chown --from=:$g1 -c :$g2 f
+chown --from=:$g1 :$g2 f; test `stat --printf=%g f` = $g2 || fail=1
 
-  # chown() must not be optimized away even when
-  # the file's owner and group already have the desired value.
-  touch f g
-  chgrp $g1 f g
-  chgrp $g2 g
-  sleep 1
-  chgrp $g1 f
+# This *should* change the group of f.
+# Though note that the diagnostic is misleading in that
+# it says the `group of `symlink'' has been changed.
+chgrp $g1 symlink; test `stat --printf=%g f` = $g1 || fail=1
+chown --from=:$g1 :$g2 f; test `stat --printf=%g f` = $g2 || fail=1
 
-  # The following no-change chgrp command is supposed to update f's ctime,
-  # but on OpenBSD, it appears to be a no-op for some file system types
-  # (at least NFS) so g's ctime is more recent.  This is not a big deal;
-  # this test works fine when the files are on a local file system (/tmp).
-  chgrp '' f
-  ls -c -t f g
+# If -R is specified without -H or L, -h is assumed.
+chgrp -h $g1 f symlink; test `stat --printf=%g symlink` = $g1 || fail=1
+chgrp -R $g2 symlink
+chown --from=:$g1 :$g2 f; test `stat --printf=%g f` = $g2 || fail=1
 
-) 2>&1 | sed "
-  s/' to .*[^0-9:].*/' to SOMENAME/
-  s/\([ :]\)$g1$/\1G1/
-  s/\([ :]\)$g2$/\1G2/
-" > actual
+# Make sure we can change the group of inaccessible files.
+chmod a-r f
+chown --from=:$g2 :$g1 f; test `stat --printf=%g f` = $g1 || fail=1
+chmod 0 f
+chown --from=:$g1 :$g2 f; test `stat --printf=%g f` = $g2 || fail=1
 
-cat <<\EOF > expected
-changed group of `f' to G1
-changed group of `f' to G2
-ownership of `f' retained
-changed group of `f' to G1
-group of `f' retained as G1
-changed group of `f' to SOMENAME
-changed group of `d/f3' to G2
-changed group of `d' to G2
-changed group of `d/f3' to G1
-changed group of `d' to G1
-changed group of `d/f3' to G2
-changed group of `d' to G2
-changed group of `d/f3' to G1
-changed group of `d' to G1
-changed group of `d' to G2
-changed ownership of `f' to :G2
-changed group of `symlink' to G1
-changed ownership of `f' to :G2
-changed ownership of `f' to :G2
-f
-g
-EOF
+# chown() must not be optimized away even when
+# the file's owner and group already have the desired value.
+rm -f f g
+touch f g
+chgrp $g1 f g
+chgrp $g2 g
+sleep 1
+chgrp $g1 f
 
-cmp expected actual \
-  || { diff expected actual 1>&2; fail=1; }
+# The following no-change chgrp command is supposed to update f's ctime,
+# but on OpenBSD, it appears to be a no-op for some file system types
+# (at least NFS) so g's ctime is more recent.  This is not a big deal;
+# this test works fine when the files are on a local file system (/tmp).
+chgrp '' f
+test "`ls -C -c -t f g`" = 'f  g' || \
+  {
+    case $host_triplet in
+      *openbsd*) echo ignoring known OpenBSD-specific chgrp failure 1>&2  ;;
+      *)         echo no-change chgrp failed to update ctime 1>&2; fail=1 ;;
+    esac
+  }
 
 (exit $fail); exit $fail
diff --git a/tests/ls-2/tests b/tests/ls-2/tests
--- a/tests/ls-2/tests
+++ b/tests/ls-2/tests
@@ -1,10 +1,42 @@
 #!/bin/sh
+# -*- perl -*-
+
+# Copyright (C) 1998, 2000, 2001, 2002, 2003, 2004, 2005, 2006 Free
+# Software Foundation, Inc.
+
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
+# 02110-1301, USA.
 
 : ${PERL=perl}
 : ${srcdir=.}
 
 $PERL -e 1 > /dev/null 2>&1 || {
   echo 1>&2 "$0: configure didn't find a usable version of Perl," \
+    "so can't run this test"
+  exit 77
+}
+
+# Set up files used by the setuid-etc tests; skip this entire test if
+# that cannot be done for some reason.
+test=../../src/test
+touch setuid && chmod u+s setuid && $test -u setuid &&
+touch setgid && chmod g+s setgid && $test -g setgid &&
+mkdir sticky && chmod +t sticky  && $test -k sticky &&
+mkdir owt    && chmod +t,o+w owt && $test -k owt &&
+mkdir owr    && chmod o+w owr || {
+  echo 1>&2 "$0: cannot create setuid/setgid/sticky files," \
     "so can't run this test"
   exit 77
 }
@@ -30,6 +62,11 @@ my $slink_d = {PRE => sub {symlink '/', 'd' or die "d: $!\n";
                            $ENV{LS_COLORS}='ln=01;36:di=01;34:or=40;31;01'
                            }};
 my $unlink_d = {POST => sub {unlink 'd' or die "d: $!\n"}};
+
+my $mkdir_d_slink = {PRE => sub {mkdir 'd',0755 or die "d: $!\n";
+				 symlink '/', 'd/s' or die "d/s: $!\n" }};
+my $rmdir_d_slink = {POST => sub {unlink 'd/s' or die "d/s: $!\n";
+				  rmdir 'd' or die "d: $!\n" }};
 
 sub make_j_d ()
 {
@@ -93,7 +130,7 @@ my @Tests =
      # From Stéphane Chazelas.
      ['no-a-isdir-b', 'no-dir d',
 	 {OUT => "d:\n"},
-	 {ERR => "ls: no-dir: No such file or directory\n"},
+	 {ERR => "ls: cannot access no-dir: No such file or directory\n"},
 	 $mkdir, $rmdir, {EXIT => 2}],
 
      ['recursive-2', '-R d', {OUT => "d:\ne\n\nd/e:\n"}, $mkdir2, $rmdir2],
@@ -108,24 +145,14 @@ my @Tests =
 	    . "\e[m"
 	 },
 
-	# This is a kludge to work around the fact that on some systems
-	# the files we've just created have a `group ID' that is not one
-	# of those associated with the current user.  Hence, attempting
-	# to do `chmod g+s setgid' fails.  This substitution maps the
-	# non-highlight 0m code to the expected one.
-	{OUT_SUBST => 's/\[0msetgid/[30;43msetgid/'},
-
-	{PRE => sub {
-	 system
-	   "touch setuid && chmod u+s setuid;"
-	  ."touch setgid && chmod g+s setgid;"
-	  ."mkdir sticky && chmod +t sticky;"
-	  ."mkdir owt    && chmod +t,o+w owt;"
-	  ."mkdir owr    && chmod o+w owr" }},
 	{POST => sub {
          unlink qw(setuid setgid);
 	 foreach my $dir (qw(owr owt sticky)) {rmdir $dir} }},
 	 ],
+
+     # For 5.97 and earlier, --file-type acted like --indicator-style=slash.
+     ['file-type', '--file-type d', {OUT => "s@\n"},
+      $mkdir_d_slink, $rmdir_d_slink],
     );
 
 my $save_temps = $ENV{SAVE_TEMPS};
diff --git a/tests/ls/follow-slink b/tests/ls/follow-slink
--- a/tests/ls/follow-slink
+++ b/tests/ls/follow-slink
@@ -1,6 +1,23 @@
 #!/bin/sh
 # make sure ls -L always follows symlinks
 
+# Copyright (C) 2000, 2002, 2004, 2006 Free Software Foundation, Inc.
+
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
+# 02110-1301, USA.
+
 if test "$VERBOSE" = yes; then
   set -x
   ls --version
@@ -14,6 +31,10 @@ trap '(exit $?); exit' 1 2 13 15
 framework_failure=0
 mkdir $tmp || framework_failure=1
 cd $tmp || framework_failure=1
+
+# Isolate output files from directory being listed
+mkdir dir || framework_failure=1
+cd dir || framework_failure=1
 ln -s link link || framework_failure=1
 
 # Make sure the symlink was created.
@@ -28,6 +49,22 @@ fi
 
 fail=0
 
+# When explicitly listing a broken link, the command must fail.
 ls -L link 2> /dev/null && fail=1
+
+# When encountering a broken link implicitly, Solaris 9 and OpenBSD 3.4
+# list the link, provided no further information about the link needed
+# to be printed.  Since POSIX does not specify one way or the other, we
+# opt for compatibility (this was broken in 5.3.0 through 5.94).
+ls -L > ../out || fail=1
+
+cd .. || fail=1
+
+cat <<\EOF > exp
+link
+EOF
+
+cmp out exp || fail=1
+test $fail = 1 && diff out exp 2> /dev/null
 
 (exit $fail); exit $fail
diff --git a/tests/ls/inode b/tests/ls/inode
--- a/tests/ls/inode
+++ b/tests/ls/inode
@@ -1,6 +1,23 @@
 #!/bin/sh
 # Make sure that ls -i works properly on symlinks.
 
+# Copyright (C) 2003, 2006 Free Software Foundation, Inc.
+
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
+# 02110-1301, USA.
+
 if test "$VERBOSE" = yes; then
   set -x
   ls --version
@@ -24,6 +41,8 @@ fi
 
 fail=0
 
+# When listed explicitly:
+
 set x `ls -Ci f slink`; shift
 test $# = 4 || fail=1
 # The inode numbers should differ.
@@ -36,12 +55,29 @@ test "$1" = "$3" || fail=1
 
 set x `ls -CHi f slink`; shift
 test $# = 4 || fail=1
-# With -H, they must be the same, too.
+# With -H, they must be the same, too, from the command line.
 # Note that POSIX says -H must make ls dereference only
 # symlinks (specified on the command line) to directories,
 # but the historical BSD meaning of -H is to dereference
 # any symlink given on the command line.  For compatibility GNU ls
 # implements the BSD semantics.
 test "$1" = "$3" || fail=1
+
+# When listed from a directory:
+
+set x `ls -Ci`; shift
+test $# = 4 || fail=1
+# The inode numbers should differ.
+test "$1" != "$3" || fail=1
+
+set x `ls -CLi`; shift
+test $# = 4 || fail=1
+# With -L, they must be the same.
+test "$1" = "$3" || fail=1
+
+set x `ls -CHi`; shift
+test $# = 4 || fail=1
+# With -H, they must be different from inside a directory.
+test "$1" != "$3" || fail=1
 
 (exit $fail); exit $fail
diff --git a/tests/misc/nohup b/tests/misc/nohup
--- a/tests/misc/nohup
+++ b/tests/misc/nohup
@@ -1,6 +1,23 @@
 #!/bin/sh
 # test nohup
 
+# Copyright (C) 2003, 2006 Free Software Foundation, Inc.
+
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
+# 02110-1301, USA.
+
 if test "$VERBOSE" = yes; then
   set -x
   nohup --version
@@ -28,20 +45,24 @@ fail=0
 nohup sh -c 'echo stdout; echo stderr 1>&2' 2>err || fail=1
 
 # Be careful.  The results of the above nohup command
-# change depending on whether stdout is redirected.
+# change depending on whether stdin and stdout are redirected.
 if test -t 1; then
   test "`cat nohup.out`" = stdout || fail=1
-  cat <<\EOF > exp || fail=1
-nohup: appending output to `nohup.out'
-stderr
-EOF
+  if test -t 0; then
+    echo 'nohup: ignoring input and appending output to `nohup.out'\'
+  else
+    echo 'nohup: appending output to `nohup.out'\'
+  fi >exp || fail=1
 else
   # Here it should not even exist.
   test -f nohup.out && fail=1
-  cat <<\EOF > exp || fail=1
-stderr
-EOF
+  if test -t 0; then
+    echo 'nohup: ignoring input' >exp
+  else
+    rm -f exp
+  fi || fail=1
 fi
+echo 'stderr' >> exp || fail=1
 
 cmp exp err || fail=1
 test $fail = 1 && diff exp err 2> /dev/null
diff --git a/tests/mkdir/p-3 b/tests/mkdir/p-3
--- a/tests/mkdir/p-3
+++ b/tests/mkdir/p-3
@@ -3,6 +3,23 @@
 # causes immediate failure.  Also, ensure that we don't create
 # subsequent, relative command-line arguments in the wrong place.
 
+# Copyright (C) 2005, 2006 Free Software Foundation, Inc.
+
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
+# 02110-1301, USA.
+
 if test "$VERBOSE" = yes; then
   set -x
   mkdir --version
@@ -20,7 +37,7 @@ mkdir -p $tmp || framework_failure=1
 cd $tmp || framework_failure=1
 mkdir no-access || framework_failure=1
 mkdir no-acce2s || framework_failure=1
-mkdir no-acce3s || framework_failure=1
+mkdir -p no-acce3s/d || framework_failure=1
 
 if test $framework_failure = 1; then
   echo "$0: failure in testing framework" 1>&2
@@ -28,26 +45,21 @@ if test $framework_failure = 1; then
 fi
 
 p=$pwd/$tmp
-(cd no-access; chmod 0 . && mkdir -p $p/a/b u/v) 2> /dev/null && fail=1
+(cd no-access && chmod 0 . && mkdir -p $p/a/b u/v) 2> /dev/null && fail=1
 test -d $p/a/b || fail=1
 
 # Same as above, but with a following *absolute* name, it should succeed
-(cd no-acce2s; chmod 0 . && mkdir -p $p/b/b $p/z) || fail=1
+(cd no-acce2s && chmod 0 . && mkdir -p $p/b/b $p/z) || fail=1
+test -d $p/b/b && test -d $p/z || fail=1
 
-test -d $p/z || fail=1
+# Same as above, but a trailing relative name in an unreadable directory
+# whose parent is inaccessible.  coreutils 5.97 fails this test.
+(cd no-acce3s/d && chmod a-rx .. && chmod a-r . && mkdir -p a/b $p/b/c d/e &&
+ test -d a/b && test -d d/e) || fail=1
+test -d $p/b/c || fail=1
 
 b=`ls $p/a|tr -d '\n'`
 # With coreutils-5.3.0, this would fail with $b=bu.
 test "x$b" = xb || fail=1
-
-# Ensure that the re_protect code is run on absolute names, even
-# after failure to return to the initial working directory.
-# This is actually a test of the underlying mkdir-p.c code.
-# The part in question cannot be tested via mkdir(1) because that
-# program cannot create leading directories that lack u=wx permissions,
-# so we have to test with install (aka ginstall in the build directory).
-(cd no-acce3s; chmod 0 . && ginstall -m 0 -d $p/c/b $p/y/z) || fail=1
-p=`ls -ld $p/y|sed 's/ .*//'`
-case $p in d---------);; *) fail=1;; esac
 
 exit $fail
diff --git a/tests/sort/sort-tests b/tests/sort/sort-tests
--- a/tests/sort/sort-tests
+++ b/tests/sort/sort-tests
@@ -2034,6 +2034,78 @@ else
   esac
 fi
 test -s o2.E || rm -f o2.E
+_POSIX2_VERSION=199209 $xx -in $srcdir/incompat1.I > incompat1.O 2> incompat1.E
+code=$?
+if test $code != 2; then
+  $echo "Test incompat1(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 2" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp incompat1.O $srcdir/incompat1.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed incompat1(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test incompat1(_POSIX2_VERSION=199209) failed: files incompat1.O and $srcdir/incompat1.X differ" 1>&2
+       (diff -c incompat1.O $srcdir/incompat1.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test incompat1(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp incompat1.O $srcdir/incompat1.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s incompat1.E || rm -f incompat1.E
+_POSIX2_VERSION=199209 $xx -fR $srcdir/incompat2.I > incompat2.O 2> incompat2.E
+code=$?
+if test $code != 2; then
+  $echo "Test incompat2(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 2" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp incompat2.O $srcdir/incompat2.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed incompat2(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test incompat2(_POSIX2_VERSION=199209) failed: files incompat2.O and $srcdir/incompat2.X differ" 1>&2
+       (diff -c incompat2.O $srcdir/incompat2.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test incompat2(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp incompat2.O $srcdir/incompat2.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s incompat2.E || rm -f incompat2.E
+_POSIX2_VERSION=199209 $xx -dfgiMnR $srcdir/incompat3.I > incompat3.O 2> incompat3.E
+code=$?
+if test $code != 2; then
+  $echo "Test incompat3(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 2" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp incompat3.O $srcdir/incompat3.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed incompat3(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test incompat3(_POSIX2_VERSION=199209) failed: files incompat3.O and $srcdir/incompat3.X differ" 1>&2
+       (diff -c incompat3.O $srcdir/incompat3.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test incompat3(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp incompat3.O $srcdir/incompat3.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s incompat3.E || rm -f incompat3.E
+_POSIX2_VERSION=199209 $xx -c -o /dev/null $srcdir/incompat4.I > incompat4.O 2> incompat4.E
+code=$?
+if test $code != 2; then
+  $echo "Test incompat4(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 2" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp incompat4.O $srcdir/incompat4.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed incompat4(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test incompat4(_POSIX2_VERSION=199209) failed: files incompat4.O and $srcdir/incompat4.X differ" 1>&2
+       (diff -c incompat4.O $srcdir/incompat4.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test incompat4(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp incompat4.O $srcdir/incompat4.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s incompat4.E || rm -f incompat4.E
 _POSIX2_VERSION=199209 $xx -k2,2 -t '\0' $srcdir/nul-tab.I > nul-tab.O 2> nul-tab.E
 code=$?
 if test $code != 0; then
@@ -2053,7 +2125,7 @@ else
 fi
 test -s nul-tab.E || rm -f nul-tab.E
 if test $errors = 0; then
-  $echo Passed all 113 tests. 1>&2
+  $echo Passed all 117 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
diff --git a/tests/tail/tail-tests b/tests/tail/tail-tests
--- a/tests/tail/tail-tests
+++ b/tests/tail/tail-tests
@@ -2052,24 +2052,24 @@ else
   esac
 fi
 test -s n-5b.E || rm -f n-5b.E
-cat $srcdir/f-1.I | $xx -f -n 1 > f-1.O 2> f-1.E
+cat $srcdir/f-pipe-1.I | POSIXLY_CORRECT=1 $xx -f -n 1 > f-pipe-1.O 2> f-pipe-1.E
 code=$?
 if test $code != 0; then
-  $echo "Test f-1 failed: $xx return code $code differs from expected value 0" 1>&2
+  $echo "Test f-pipe-1(POSIXLY_CORRECT=1) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
-  cmp f-1.O $srcdir/f-1.X > /dev/null 2>&1
+  cmp f-pipe-1.O $srcdir/f-pipe-1.X > /dev/null 2>&1
   case $? in
-    0) if test "$VERBOSE"; then $echo "passed f-1"; fi;;
-    1) $echo "Test f-1 failed: files f-1.O and $srcdir/f-1.X differ" 1>&2
-       (diff -c f-1.O $srcdir/f-1.X) 2> /dev/null
+    0) if test "$VERBOSE"; then $echo "passed f-pipe-1(POSIXLY_CORRECT=1)"; fi;;
+    1) $echo "Test f-pipe-1(POSIXLY_CORRECT=1) failed: files f-pipe-1.O and $srcdir/f-pipe-1.X differ" 1>&2
+       (diff -c f-pipe-1.O $srcdir/f-pipe-1.X) 2> /dev/null
        errors=`expr $errors + 1`;;
-    2) $echo "Test f-1 may have failed." 1>&2
-       $echo The command "cmp f-1.O $srcdir/f-1.X" failed. 1>&2
+    2) $echo "Test f-pipe-1(POSIXLY_CORRECT=1) may have failed." 1>&2
+       $echo The command "cmp f-pipe-1.O $srcdir/f-pipe-1.X" failed. 1>&2
        errors=`expr $errors + 1`;;
   esac
 fi
-test -s f-1.E || rm -f f-1.E
+test -s f-pipe-1.E || rm -f f-pipe-1.E
 if test $errors = 0; then
   $echo Passed all 114 tests. 1>&2
 else
