Snapshot from coreutils-6.10.tar.lzma

diff --git a/Makefile.maint b/Makefile.maint
--- a/Makefile.maint
+++ b/Makefile.maint
@@ -2,12 +2,12 @@
 # This Makefile fragment is shared between the coreutils,
 # CPPI, Bison, and Autoconf.
 
-## Copyright (C) 2001-2007 Free Software Foundation, Inc.
+## Copyright (C) 2001-2008 Free Software Foundation, Inc.
 ##
-## This program is free software; you can redistribute it and/or modify
+## This program is free software: you can redistribute it and/or modify
 ## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation; either version 2, or (at your option)
-## any later version.
+## the Free Software Foundation, either version 3 of the License, or
+## (at your option) any later version.
 ##
 ## This program is distributed in the hope that it will be useful,
 ## but WITHOUT ANY WARRANTY; without even the implied warranty of
@@ -15,9 +15,7 @@
 ## GNU General Public License for more details.
 ##
 ## You should have received a copy of the GNU General Public License
-## along with this program; if not, write to the Free Software
-## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
-## 02110-1301, USA.
+## along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 # This is reported not to work with make-3.79.1
 # ME := $(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST))
@@ -46,9 +44,15 @@ endif
 PREV_VERSION := $(shell cat $(prev_version_file))
 VERSION_REGEXP = $(subst .,\.,$(VERSION))
 
+ifeq ($(VC),$(GIT))
+this-vc-tag = v$(VERSION)
+this-vc-tag-regexp = v$(VERSION_REGEXP)
+else
 tag-package = $(shell echo "$(PACKAGE)" | tr '[:lower:]' '[:upper:]')
 tag-this-version = $(subst .,_,$(VERSION))
 this-vc-tag = $(tag-package)-$(tag-this-version)
+this-vc-tag-regexp = $(this-vc-tag)
+endif
 my_distdir = $(PACKAGE)-$(VERSION)
 
 # Old releases are stored here.
@@ -122,7 +126,14 @@ sc_space_tab:
 # Instead, use strto* functions.
 sc_prohibit_atoi_atof:
 	@grep -nE '\<([fs]?scanf|ato([filq]|ll))\>' $$($(CVS_LIST_EXCEPT)) && \
-	  { echo '$(ME): do not use *scan''f, ato''f, ato''i, ato''l, ato''ll, or ato''q'	\
+	  { echo '$(ME): do not use *scan''f, ato''f, ato''i, ato''l, ato''ll, ato''q, or ss''canf'	\
+		1>&2; exit 1; } || :
+
+# Use STREQ rather than comparing strcmp == 0, or != 0.
+sc_prohibit_strcmp:
+	@grep -nE '! *str''cmp \(|\<str''cmp \([^)]+\) *==' \
+	    $$($(CVS_LIST_EXCEPT)) && \
+	  { echo '$(ME): use STREQ in place of the above uses of str''cmp' \
 		1>&2; exit 1; } || :
 
 # Using EXIT_SUCCESS as the first argument to error is misleading,
@@ -163,6 +174,30 @@ sc_prohibit_assert_without_use:
 	  grep -L '\<assert (' $$files					\
 	      | grep . &&						\
 	    { echo "$(ME): the above files include <assert.h> but don't use it" \
+		  1>&2; exit 1; } || :;					\
+	else :;								\
+	fi
+
+# Don't include quotearg.h unless you use one of its functions.
+sc_prohibit_quotearg_without_use:
+	@if $(CVS_LIST_EXCEPT) | grep '\.c$$' > /dev/null; then		\
+	  files=$$(grep -l '# *include "quotearg\.h"'			\
+		    $$($(CVS_LIST_EXCEPT) | grep '\.c$$')) &&		\
+	  grep -LE '\<quotearg(_[^ ]+)? \(' $$files			\
+	      | grep . &&						\
+	    { echo "$(ME): the above files include "quotearg.h" but don't use it" \
+		  1>&2; exit 1; } || :;					\
+	else :;								\
+	fi
+
+# Don't include quote.h unless you use one of its functions.
+sc_prohibit_quote_without_use:
+	@if $(CVS_LIST_EXCEPT) | grep '\.c$$' > /dev/null; then		\
+	  files=$$(grep -l '# *include "quote\.h"'			\
+		    $$($(CVS_LIST_EXCEPT) | grep '\.c$$')) &&		\
+	  grep -LE '\<quote(_n)? \(' $$files			\
+	      | grep . &&						\
+	    { echo "$(ME): the above files include "quote.h" but don't use it" \
 		  1>&2; exit 1; } || :;					\
 	else :;								\
 	fi
@@ -324,21 +359,26 @@ sc_useless_cpp_parens:
 	  { echo '$(ME): found useless parentheses in cpp directive'	\
 		1>&2; exit 1; } || :
 
+# Require the latest GPL.
+sc_GPL_version:
+	@grep -n 'either ''version [^3]' $$($(CVS_LIST_EXCEPT)) &&	\
+	  { echo '$(ME): GPL vN, N!=3' 1>&2; exit 1; } || :
+
 # Ensure that the c99-to-c89 patch applies cleanly.
 patch-check:
 	rm -rf src-c89 $@.1 $@.2
 	cp -a src src-c89
-	(cd src-c89; patch -p2 -V never --fuzz=0) < src/c99-to-c89.diff \
+	(cd src-c89; patch -p1 -V never --fuzz=0) < src/c99-to-c89.diff \
 	  > $@.1 2>&1
-	if test "$${REGEN_PATCH+set}" = set; then \
-	  diff -upr src src-c89 > new-diff || : ; fi
+	if test "$$REGEN_PATCH" = yes; then \
+	  diff -upr src src-c89 | sed 's,src-c89/,src/,' \
+	    | grep -v '^Only in' > new-diff || : ; fi
 	grep -v '^patching file ' $@.1 > $@.2 || :
 	msg=ok; test -s $@.2 && msg='fuzzy patch' || : ;	\
 	rm -f src-c89/*.o || msg='rm failed';			\
 	$(MAKE) -C src-c89 CFLAGS='-Wdeclaration-after-statement -Werror' \
 	  || msg='compile failure with extra options';		\
-	rm -rf src-c89 $@.1 $@.2;				\
-	test "$$msg" = ok && : || echo "$$msg" 1>&2;		\
+	test "$$msg" = ok && rm -rf src-c89 $@.1 $@.2 || echo "$$msg" 1>&2; \
 	test "$$msg" = ok
 
 # Ensure that date's --help output stays in sync with the info
@@ -450,7 +490,9 @@ writable-files:
 
 v_etc_file = lib/version-etc.c
 sample-test = tests/sample-test
+texi = doc/$(PACKAGE).texi
 # Make sure that the copyright date in $(v_etc_file) is up to date.
+# Do the same for the $(sample-test) and the main doc/.texi file.
 copyright-check:
 	@if test -f $(v_etc_file); then \
 	  grep 'enum { COPYRIGHT_YEAR = '$$(date +%Y)' };' $(v_etc_file) \
@@ -464,21 +506,11 @@ copyright-check:
 	  || { echo 'out of date copyright in $(sample-test); update it' 1>&2; \
 	       exit 1; }; \
 	fi
-
-
-# Sanity checks with the repository.
-# Abort early if this tag has already been used.
-vc-tag-check:
-	used=no;							\
-	if $(VC) --help | grep CVS; then				\
-	  $(CVS) -n log -h README|grep -e $(this-vc-tag): >/dev/null	\
-	    && used=yes;						\
-	else								\
-	  $(GIT) tag -l '^$(this-vc-tag)$$' && used=yes;		\
-	fi;								\
-	if test "$$used" = yes; then					\
-	  echo "$(this-vc-tag) has already been used; not tagging" 1>&2; \
-	  exit 1;							\
+	@if test -f $(texi); then \
+	  grep 'Copyright @copyright{} .*'$$(date +%Y)' Free' $(texi) \
+	    >/dev/null \
+	  || { echo 'out of date copyright in $(texi); update it' 1>&2; \
+	       exit 1; }; \
 	fi
 
 vc-diff-check:
@@ -491,18 +523,16 @@ vc-diff-check:
 	  rm vc-diffs;						\
 	fi
 
-cvs-check: vc-diff-check vc-tag-check
+cvs-check: vc-diff-check
 
 maintainer-distcheck:
 	$(MAKE) distcheck
 	$(MAKE) my-distcheck
 
 
-# Tag before making distribution.  Also, don't make a distribution if
-# checks fail.  Also, make sure the NEWS file is up-to-date.
-# FIXME: use dist-hook/my-dist like distcheck-hook/my-distcheck.
+# Don't make a distribution if checks fail.
+# Also, make sure the NEWS file is up-to-date.
 vc-dist: $(local-check) cvs-check maintainer-distcheck
-	$(VC-tag) $(this-vc-tag)
 	$(MAKE) dist
 
 # Use this to make sure we don't run these programs when building
@@ -514,16 +544,28 @@ null_AM_MAKEFLAGS = \
   AUTOHEADER=false \
   MAKEINFO=false
 
+built_programs = $$(cd src && MAKEFLAGS= $(MAKE) -s built_programs.list)
+
 warn_cflags = -Dlint -O -Werror -Wall -Wformat -Wshadow -Wpointer-arith
+bin=bin-$$$$
+
+write_loser = printf '\#!%s\necho $$0: bad path 1>&2; exit 1\n' '$(SHELL)'
 
 # Use -Wformat -Werror to detect format-string/arg-list mismatches.
 # Also, check for shadowing problems with -Wshadow, and for pointer
 # arithmetic problems with -Wpointer-arith.
 # These CFLAGS are pretty strict.  If you build this target, you probably
 # have to have a recent version of gcc and glibc headers.
+# The for-loop below ensures that there is a bin/ directory full of all
+# of the programs under test (except the few that are required for basic
+# Makefile rules), all symlinked to the just-built "false" program.
+# This is to ensure that if ever a test neglects to make PATH include
+# the build srcdir, these always-failing programs will run.
+# Otherwise, it is too easy to test the wrong programs.
+# Note that "false" itself is a symlink to true, so it too will malfunction.
 TMPDIR ?= /tmp
 t=$(TMPDIR)/$(PACKAGE)/test
-my-distcheck: $(local-check) $(release_archive_dir)/$(prev-tgz)
+my-distcheck: $(local-check) $(release_archive_dir)/$(prev-tgz) check
 	-rm -rf $(t)
 	mkdir -p $(t)
 	GZIP=$(GZIP_ENV) $(AMTAR) -C $(t) -zxf $(distdir).tar.gz
@@ -532,7 +574,20 @@ my-distcheck: $(local-check) $(release_archive_dir)/$(prev-tgz)
 	  && $(MAKE) CFLAGS='$(warn_cflags)'		\
 	      AM_MAKEFLAGS='$(null_AM_MAKEFLAGS)'	\
 	  && $(MAKE) dvi				\
-	  && $(MAKE) check				\
+	  && mkdir $(bin)				\
+	  && ($(write_loser)) > $(bin)/loser            \
+	  && chmod a+x $(bin)/loser                     \
+	  && for i in $(built_programs); do		\
+	       case $$i in				\
+		 rm|expr|basename|echo|sort|ls|tr);;	\
+		 cat|dirname|mv|wc);;			\
+		 *) ln $(bin)/loser $(bin)/$$i;;	\
+	       esac;					\
+	     done					\
+	  && ln -sf ../src/true $(bin)/false		\
+	  && PATH=`pwd`/$(bin):$$PATH $(MAKE) -C tests check \
+	  && $(MAKE) -C gnulib-tests check		\
+	  && rm -rf $(bin)				\
 	  && $(MAKE) distclean
 	(cd $(t) && mv $(distdir) $(distdir).old	\
 	  && $(AMTAR) -zxf - ) < $(distdir).tar.gz
@@ -541,7 +596,7 @@ my-distcheck: $(local-check) $(release_archive_dir)/$(prev-tgz)
 	  cd $(t)/$(distdir)						\
 	    && (cd src && patch -V never --fuzz=0 <c99-to-c89.diff)	\
 	    && ./configure --disable-largefile				\
-	         CFLAGS='-Werror -ansi -pedantic -Wno-long-long'	\
+	         CFLAGS='-Werror -ansi -Wno-long-long'			\
 	    && $(MAKE);							\
 	fi
 	-rm -rf $(t)
@@ -562,9 +617,14 @@ rel-check:
 	md5sum -c $$md5_tmp < $$tarz
 
 prev-tgz = $(PACKAGE)-$(PREV_VERSION).tar.gz
+
+# FIXME: stop distributing xdelta files in 2008, unless someone speaks up.
+# So far, not one person has said they'd miss this.
 xd-delta = $(PACKAGE)-$(PREV_VERSION)-$(VERSION).xdelta
 
 rel-files = $(xd-delta) $(DIST_ARCHIVES)
+
+gnulib-version = $$(cd $(gnulib_dir) && git describe)
 
 # Approximate the date of last gnulib "update" by the ChangeLog file's
 # mtime, and provide that date in the announcement.
@@ -579,7 +639,7 @@ announcement: NEWS ChangeLog $(rel-files)
 	    --gpg-key-id=$(gpg_key_ID)					\
 	    --news=NEWS							\
 	    --bootstrap-tools=autoconf,automake,bison,gnulib		\
-	    --gnulib-snapshot-time-stamp="$$utc_date"			\
+	    --gnulib-version=$(gnulib-version)				\
 	    $(addprefix --url-dir=, $(url_dir_list))
 
 ## ---------------- ##
@@ -606,12 +666,13 @@ $(xd-delta): $(release_archive_dir)/$(prev-tgz) $(distdir).tar.gz
 	xdelta delta -9 $^ $@ || :
 
 .PHONY: alpha beta major
-alpha beta major: news-date-check changelog-check $(local-check) writable-files
+alpha beta major: $(local-check) writable-files
 	test $@ = major						\
 	  && { echo $(VERSION) | grep -E '^[0-9]+(\.[0-9]+)+$$'	\
 	       || { echo "invalid version string: $(VERSION)" 1>&2; exit 1;};}\
 	  || :
 	$(MAKE) vc-dist
+	$(MAKE) news-date-check changelog-check
 	$(MAKE) $(xd-delta)
 	$(MAKE) -s announcement RELEASE_TYPE=$@ > /tmp/announce-$(my_distdir)
 	ln $(rel-files) $(release_archive_dir)
diff --git a/tests/cut/cut-tests b/tests/cut/cut-tests
--- a/tests/cut/cut-tests
+++ b/tests/cut/cut-tests
@@ -3096,8 +3096,224 @@ else
   esac
 fi
 test -s od-overlap5.E || rm -f od-overlap5.E
+$xx -f 2-0 $srcdir/inval1.I > inval1.O 2> inval1.E
+code=$?
+if test $code != 1; then
+  $echo "Test inval1(F) failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp inval1.O $srcdir/inval1.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed inval1(F)"; fi;;
+    1) $echo "Test inval1(F) failed: files inval1.O and $srcdir/inval1.X differ" 1>&2
+       (diff -c inval1.O $srcdir/inval1.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test inval1(F) may have failed." 1>&2
+       $echo The command "cmp inval1.O $srcdir/inval1.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s inval1.E || rm -f inval1.E
+$xx -f 2-0 < $srcdir/inval1.I > inval1.O 2> inval1.E
+code=$?
+if test $code != 1; then
+  $echo "Test inval1(<) failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp inval1.O $srcdir/inval1.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed inval1(<)"; fi;;
+    1) $echo "Test inval1(<) failed: files inval1.O and $srcdir/inval1.X differ" 1>&2
+       (diff -c inval1.O $srcdir/inval1.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test inval1(<) may have failed." 1>&2
+       $echo The command "cmp inval1.O $srcdir/inval1.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s inval1.E || rm -f inval1.E
+$xx -f - $srcdir/inval2.I > inval2.O 2> inval2.E
+code=$?
+if test $code != 1; then
+  $echo "Test inval2(F) failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp inval2.O $srcdir/inval2.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed inval2(F)"; fi;;
+    1) $echo "Test inval2(F) failed: files inval2.O and $srcdir/inval2.X differ" 1>&2
+       (diff -c inval2.O $srcdir/inval2.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test inval2(F) may have failed." 1>&2
+       $echo The command "cmp inval2.O $srcdir/inval2.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s inval2.E || rm -f inval2.E
+$xx -f - < $srcdir/inval2.I > inval2.O 2> inval2.E
+code=$?
+if test $code != 1; then
+  $echo "Test inval2(<) failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp inval2.O $srcdir/inval2.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed inval2(<)"; fi;;
+    1) $echo "Test inval2(<) failed: files inval2.O and $srcdir/inval2.X differ" 1>&2
+       (diff -c inval2.O $srcdir/inval2.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test inval2(<) may have failed." 1>&2
+       $echo The command "cmp inval2.O $srcdir/inval2.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s inval2.E || rm -f inval2.E
+$xx -f 4,- $srcdir/inval3.I > inval3.O 2> inval3.E
+code=$?
+if test $code != 1; then
+  $echo "Test inval3(F) failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp inval3.O $srcdir/inval3.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed inval3(F)"; fi;;
+    1) $echo "Test inval3(F) failed: files inval3.O and $srcdir/inval3.X differ" 1>&2
+       (diff -c inval3.O $srcdir/inval3.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test inval3(F) may have failed." 1>&2
+       $echo The command "cmp inval3.O $srcdir/inval3.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s inval3.E || rm -f inval3.E
+$xx -f 4,- < $srcdir/inval3.I > inval3.O 2> inval3.E
+code=$?
+if test $code != 1; then
+  $echo "Test inval3(<) failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp inval3.O $srcdir/inval3.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed inval3(<)"; fi;;
+    1) $echo "Test inval3(<) failed: files inval3.O and $srcdir/inval3.X differ" 1>&2
+       (diff -c inval3.O $srcdir/inval3.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test inval3(<) may have failed." 1>&2
+       $echo The command "cmp inval3.O $srcdir/inval3.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s inval3.E || rm -f inval3.E
+$xx -f 1-2,- $srcdir/inval4.I > inval4.O 2> inval4.E
+code=$?
+if test $code != 1; then
+  $echo "Test inval4(F) failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp inval4.O $srcdir/inval4.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed inval4(F)"; fi;;
+    1) $echo "Test inval4(F) failed: files inval4.O and $srcdir/inval4.X differ" 1>&2
+       (diff -c inval4.O $srcdir/inval4.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test inval4(F) may have failed." 1>&2
+       $echo The command "cmp inval4.O $srcdir/inval4.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s inval4.E || rm -f inval4.E
+$xx -f 1-2,- < $srcdir/inval4.I > inval4.O 2> inval4.E
+code=$?
+if test $code != 1; then
+  $echo "Test inval4(<) failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp inval4.O $srcdir/inval4.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed inval4(<)"; fi;;
+    1) $echo "Test inval4(<) failed: files inval4.O and $srcdir/inval4.X differ" 1>&2
+       (diff -c inval4.O $srcdir/inval4.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test inval4(<) may have failed." 1>&2
+       $echo The command "cmp inval4.O $srcdir/inval4.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s inval4.E || rm -f inval4.E
+$xx -f 1-,- $srcdir/inval5.I > inval5.O 2> inval5.E
+code=$?
+if test $code != 1; then
+  $echo "Test inval5(F) failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp inval5.O $srcdir/inval5.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed inval5(F)"; fi;;
+    1) $echo "Test inval5(F) failed: files inval5.O and $srcdir/inval5.X differ" 1>&2
+       (diff -c inval5.O $srcdir/inval5.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test inval5(F) may have failed." 1>&2
+       $echo The command "cmp inval5.O $srcdir/inval5.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s inval5.E || rm -f inval5.E
+$xx -f 1-,- < $srcdir/inval5.I > inval5.O 2> inval5.E
+code=$?
+if test $code != 1; then
+  $echo "Test inval5(<) failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp inval5.O $srcdir/inval5.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed inval5(<)"; fi;;
+    1) $echo "Test inval5(<) failed: files inval5.O and $srcdir/inval5.X differ" 1>&2
+       (diff -c inval5.O $srcdir/inval5.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test inval5(<) may have failed." 1>&2
+       $echo The command "cmp inval5.O $srcdir/inval5.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s inval5.E || rm -f inval5.E
+$xx -f -1,- $srcdir/inval6.I > inval6.O 2> inval6.E
+code=$?
+if test $code != 1; then
+  $echo "Test inval6(F) failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp inval6.O $srcdir/inval6.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed inval6(F)"; fi;;
+    1) $echo "Test inval6(F) failed: files inval6.O and $srcdir/inval6.X differ" 1>&2
+       (diff -c inval6.O $srcdir/inval6.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test inval6(F) may have failed." 1>&2
+       $echo The command "cmp inval6.O $srcdir/inval6.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s inval6.E || rm -f inval6.E
+$xx -f -1,- < $srcdir/inval6.I > inval6.O 2> inval6.E
+code=$?
+if test $code != 1; then
+  $echo "Test inval6(<) failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp inval6.O $srcdir/inval6.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed inval6(<)"; fi;;
+    1) $echo "Test inval6(<) failed: files inval6.O and $srcdir/inval6.X differ" 1>&2
+       (diff -c inval6.O $srcdir/inval6.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test inval6(<) may have failed." 1>&2
+       $echo The command "cmp inval6.O $srcdir/inval6.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s inval6.E || rm -f inval6.E
 if test $errors = 0; then
-  $echo Passed all 171 tests. 1>&2
+  $echo Passed all 183 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
diff --git a/tests/du/basic b/tests/du/basic
--- a/tests/du/basic
+++ b/tests/du/basic
@@ -3,9 +3,9 @@
 
 # Copyright (C) 2003, 2006-2007 Free Software Foundation, Inc.
 
-# This program is free software; you can redistribute it and/or modify
+# This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 
 # This program is distributed in the hope that it will be useful,
@@ -14,9 +14,7 @@
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
-# 02110-1301, USA.
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 if test "$VERBOSE" = yes; then
   set -x
@@ -24,30 +22,17 @@ if test "$VERBOSE" = yes; then
 fi
 
 # DU_BLOCK_SIZE could cause problems
-. $srcdir/../envvar-check
 . $srcdir/../lang-default
+. $srcdir/../test-lib.sh
 
-pwd=`pwd`
-t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
-trap '(exit $?); exit $?' 1 2 13 15
-
-framework_failure=0
-mkdir -p $tmp || framework_failure=1
-cd $tmp || framework_failure=1
-mkdir -p a/b d d/sub || framework_failure=1
+mkdir -p a/b d d/sub || framework_failure
 
 # Ensure that these files contain more than 64 bytes, so that we don't
 # immediately disqualify file systems (e.g., NetApp) on which smaller
 # files take up zero disk blocks.
-printf '%*s' 257 make-sure-the-file-is-non-empty > a/b/F || framework_failure=1
+printf '%*s' 257 make-sure-the-file-is-non-empty > a/b/F || framework_failure
 printf %4096s x > d/1
 cp d/1 d/sub/2
-
-if test $framework_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  (exit 1); exit 1
-fi
 
 fail=0
 
@@ -77,8 +62,7 @@ $a	a       # size of dir entry, a
 $tot	a
 EOF
 
-cmp out exp || fail=1
-test $fail = 1 && diff -u out exp 2> /dev/null
+compare out exp || fail=1
 
 # Perform this test only if "." is on a local file system.
 # Otherwise, it would fail e.g., on an NFS-mounted Solaris ZFS file system.
@@ -106,8 +90,7 @@ $s2	d/sub
 $d1	d           # d + d/1; don't count the dir. entry for d/sub
 EOF
 
-  cmp out exp || fail=1
-  test $fail = 1 && diff out exp 2> /dev/null
+  compare out exp || fail=1
 fi
 
 (exit $fail); exit $fail
diff --git a/tests/misc/cut b/tests/misc/cut
--- a/tests/misc/cut
+++ b/tests/misc/cut
@@ -1,11 +1,11 @@
 #!/bin/sh
 # Test "cut".                                                   -*- perl -*-
 
-# Copyright (C) 2006 Free Software Foundation, Inc.
+# Copyright (C) 2006, 2007 Free Software Foundation, Inc.
 
-# This program is free software; you can redistribute it and/or modify
+# This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 
 # This program is distributed in the hope that it will be useful,
@@ -14,20 +14,19 @@
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
-# 02110-1301, USA.
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 : ${PERL=perl}
 : ${srcdir=.}
 
-$PERL -e 1 > /dev/null 2>&1 || {
+$PERL -e 'use warnings;' > /dev/null 2>&1 || {
   echo 1>&2 "$0: configure didn't find a usable version of Perl," \
     "so can't run this test"
   exit 77
 }
 
-exec $PERL -w -I$srcdir/.. -MCoreutils -- - <<\EOF
+me=`echo $0|sed 's,.*/,,'`
+exec $PERL -w -I$srcdir/.. -MCoreutils -M"CuTmpdir qw($me)" -- - <<\EOF
 require 5.003;
 use strict;
 
@@ -36,16 +35,29 @@ use strict;
 # Turn off localisation of executable's ouput.
 @ENV{qw(LANGUAGE LANG LC_ALL)} = ('C') x 3;
 
+my $prog = 'cut';
+my $diag = <<DIAG_EOF;
+$prog: fields and positions are numbered from 1
+Try \`cut --help' for more information.
+DIAG_EOF
+
 my @Tests =
   (
-  # Provoke a double-free in cut from coreutils-6.7.
-  ['dbl-free', '-f2-', {IN=>{f=>'x'}}, {IN=>{g=>'y'}}, {OUT=>"x\ny\n"}],
+   # Provoke a double-free in cut from coreutils-6.7.
+   ['dbl-free', '-f2-', {IN=>{f=>'x'}}, {IN=>{g=>'y'}}, {OUT=>"x\ny\n"}],
+
+   # This failed (as it should) even before coreutils-6.9.90,
+   # but cut from 6.9.90 produces a more useful diagnostic.
+   ['zero-1', '-b0',   {ERR=>$diag}, {EXIT => 1} ],
+
+   # Up to coreutils-6.9, specifying a range of 0-2 was not an error.
+   # It was treated just like "-2".
+   ['zero-2', '-f0-2', {ERR=>$diag}, {EXIT => 1} ],
   );
 
 my $save_temps = $ENV{DEBUG};
 my $verbose = $ENV{VERBOSE};
 
-my $prog = 'cut';
 my $fail = run_tests ($ME, $prog, \@Tests, $save_temps, $verbose);
 exit $fail;
 EOF
diff --git a/tests/misc/sort-rand b/tests/misc/sort-rand
--- a/tests/misc/sort-rand
+++ b/tests/misc/sort-rand
@@ -1,11 +1,11 @@
 #!/bin/sh
 # Ensure that sort --sort-random doesn't sort.
 
-# Copyright (C) 2005, 2006 Free Software Foundation, Inc.
+# Copyright (C) 2005-2007 Free Software Foundation, Inc.
 
-# This program is free software; you can redistribute it and/or modify
+# This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 
 # This program is distributed in the hope that it will be useful,
@@ -14,29 +14,16 @@
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
-# 02110-1301, USA.
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 if test "$VERBOSE" = yes; then
   set -x
   sort --version
 fi
 
-pwd=`pwd`
-t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
-trap '(exit $?); exit $?' 1 2 13 15
+. $srcdir/../test-lib.sh
 
-framework_failure=0
-mkdir -p $tmp || framework_failure=1
-cd $tmp || framework_failure=1
-seq 100 > in || framework_failure=1
-
-if test $framework_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  (exit 1); exit 1
-fi
+seq 100 > in || framework_failure
 
 fail=0
 
@@ -45,10 +32,24 @@ sort --random-sort in > out || fail=1
 # Fail if the input is the same as the output.
 # This is a probabilistic test :-)
 # However, the odds of failure are very low: 1 in 100! (~ 1 in 10^158)
-cmp in out > /dev/null && { fail=1; echo "not random?" 1>&2; }
+compare in out > /dev/null && { fail=1; echo "not random?" 1>&2; }
 
 # Fail if the sorted output is not the same as the input.
 sort -n out > out1
-cmp in out1 || { fail=1; echo "not a permutation" 1>&2; }
+compare in out1 || { fail=1; echo "not a permutation" 1>&2; }
+
+# If locale is available then use it to find a random non-C locale.
+if (locale --version) > /dev/null 2>&1; then
+  locale=`locale -a | sort --random-sort | awk '/^.._/{print;exit}'`
+  LC_ALL=$locale sort --random-sort in > out1 || fail=1
+  LC_ALL=$locale sort --random-sort in > out2 || fail=1
+
+  # Fail if the output "randomly" is the same twice in a row.
+  compare out1 out2 > /dev/null && { fail=1; echo "not random with LC_ALL=$locale" 1>&2; }
+
+  # Fail if the sorted output is not the same as the input.
+  sort -n out > out1
+  compare in out1 || { fail=1; echo "not a permutation with LC_ALL=$locale" 1>&2; }
+fi
 
 (exit $fail); exit $fail
diff --git a/tests/mv/childproof b/tests/mv/childproof
--- a/tests/mv/childproof
+++ b/tests/mv/childproof
@@ -1,12 +1,13 @@
 #!/bin/sh
-# Ensure that cp/mv don't clobber a just-copied file.
-# With fileutils-4.1 and earlier, this test would fail.
+# Ensure that cp/mv/ln don't clobber a just-copied/moved/linked file.
+# With fileutils-4.1 and earlier, this test would fail for cp and mv.
+# With coreutils-6.9 and earlier, this test would fail for ln.
 
-# Copyright (C) 2001, 2004, 2006 Free Software Foundation, Inc.
+# Copyright (C) 2001, 2004, 2006-2007 Free Software Foundation, Inc.
 
-# This program is free software; you can redistribute it and/or modify
+# This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 
 # This program is distributed in the hope that it will be useful,
@@ -15,36 +16,22 @@
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
-# 02110-1301, USA.
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 if test "$VERBOSE" = yes; then
   set -x
   cp --version
   mv --version
+  ln --version
 fi
 
-. $srcdir/../envvar-check
 . $srcdir/../lang-default
-PRIV_CHECK_ARG=require-non-root . $srcdir/../priv-check
+. $srcdir/../test-lib.sh
+skip_if_root_
 
-pwd=`pwd`
-tmp=childproof.$$
-trap 'status=$?; cd "$pwd" && rm -rf $tmp && exit $status' 0
-trap '(exit $?); exit' 1 2 13 15
-
-framework_failure=0
-mkdir $tmp || framework_failure=1
-cd $tmp || framework_failure=1
-mkdir a b c || framework_failure=1
-echo a > a/f || framework_failure=1
-echo b > b/f || framework_failure=1
-
-if test $framework_failure = 1; then
-  echo 'failure in testing framework' 1>&2
-  (exit 1); exit 1
-fi
+mkdir a b c || framework_failure
+echo a > a/f || framework_failure
+echo b > b/f || framework_failure
 
 fail=0
 
@@ -88,5 +75,16 @@ test -f b/f || fail=1  # b/f should remain
 test -f b/g && fail=1  # b/g should have been moved
 test -f c/f || fail=1
 test -f c/g || fail=1
+
+# Test ln -f.
+
+rm -f a/f b/f c/f
+echo a > a/f || fail=1
+echo b > b/f || fail=1
+ln -f a/f b/f c 2> /dev/null && fail=1
+# a/f and c/f must be linked
+test `stat --format %i a/f` = `stat --format %i c/f` || fail=1
+# b/f and c/f must not be linked
+test `stat --format %i b/f` = `stat --format %i c/f` && fail=1
 
 (exit $fail); exit $fail
diff --git a/tests/mv/mv-special-1 b/tests/mv/mv-special-1
--- a/tests/mv/mv-special-1
+++ b/tests/mv/mv-special-1
@@ -1,12 +1,12 @@
 #! /bin/sh
 # Test "mv" with special files.
 
-# Copyright (C) 1998, 1999, 2000, 2002, 2004, 2005, 2006 Free Software
+# Copyright (C) 1998, 1999, 2000, 2002, 2004-2007 Free Software
 # Foundation, Inc.
 
-# This program is free software; you can redistribute it and/or modify
+# This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 
 # This program is distributed in the hope that it will be useful,
@@ -15,50 +15,32 @@
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
-# 02110-1301, USA.
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 if test "$VERBOSE" = yes; then
   set -x
   mv --version
 fi
 
-pwd=`pwd`
-tmp=mv-spec.$$
-trap 'status=$?; cd "$pwd" && exec 1>&2; rm -rf $tmp $other_partition_tmpdir && exit $status' 0
-trap '(exit $?); exit' 1 2 13 15
-
-. $srcdir/../other-fs-tmpdir
-. $srcdir/../envvar-check
-# Make sure we get English translations.
 . $srcdir/../lang-default
-
-if test -z "$other_partition_tmpdir"; then
-  (exit 77); exit 77
-fi
+. $srcdir/../test-lib.sh
+cleanup_() { rm -rf "$other_partition_tmpdir"; }
+. "$abs_top_srcdir/tests/other-fs-tmpdir"
 
 null=mv-null
 dir=mv-dir
 
-framework_failure=0
-mkdir $tmp || framework_failure=1
-cd $tmp || framework_failure=1
-rm -f $null || framework_failure=1
-mknod $null p || framework_failure=1
-test -p $null || framework_failure=1
-mkdir -p $dir/a/b/c $dir/d/e/f || framework_failure=1
-touch $dir/a/b/c/file1 $dir/d/e/f/file2 || framework_failure=1
+rm -f $null || framework_failure
+mknod $null p || framework_failure
+test -p $null || framework_failure
+mkdir -p $dir/a/b/c $dir/d/e/f || framework_failure
+touch $dir/a/b/c/file1 $dir/d/e/f/file2 || framework_failure
 
-if test $framework_failure = 1; then
-  echo '********************************************'
-  echo 'NOTICE: unable to create test prerequisites'
-  echo '********************************************'
-  # exit 77 here to indicate that we couldn't run the test.
-  # At least running on SunOS 4.1.4, using a directory NFS mounted
-  # from an OpenBSD system, the above mknod fails.
-  (exit 77); exit 77
-fi
+# We used to...
+# exit 77 here to indicate that we couldn't run the test.
+# At least running on SunOS 4.1.4, using a directory NFS mounted
+# from an OpenBSD system, the above mknod fails.
+# It's not worth making an exception any more.
 
 fail=0
 mv --verbose $null $dir $other_partition_tmpdir > out || fail=1
@@ -89,7 +71,7 @@ cat <<EOF | sort > exp
 \`$dir/d/e/f/file2' -> \`XXX/$dir/d/e/f/file2'
 EOF
 
-cmp out2 exp || fail=1
+compare out2 exp || fail=1
 
 # cd $other_partition_tmpdir
 # ls -l -A -R $other_partition_tmpdir
diff --git a/tests/rm/fail-2eperm b/tests/rm/fail-2eperm
--- a/tests/rm/fail-2eperm
+++ b/tests/rm/fail-2eperm
@@ -2,11 +2,11 @@
 # Like fail-eperm, but the failure must be for a file encountered
 # while trying to remove the containing directory with the sticky bit set.
 
-# Copyright (C) 2003, 2006 Free Software Foundation, Inc.
+# Copyright (C) 2003, 2006-2007 Free Software Foundation, Inc.
 
-# This program is free software; you can redistribute it and/or modify
+# This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 
 # This program is distributed in the hope that it will be useful,
@@ -15,9 +15,7 @@
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
-# 02110-1301, USA.
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 if test "$VERBOSE" = yes; then
   set -x
@@ -26,39 +24,26 @@ fi
 
 . $srcdir/../lang-default
 PRIV_CHECK_ARG=require-root . $srcdir/../priv-check
-
-pwd=`pwd`
-t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
-trap '(exit $?); exit $?' 1 2 13 15
-
-framework_failure=0
-mkdir -p $tmp || framework_failure=1
-cd $tmp || framework_failure=1
+. $srcdir/../test-lib.sh
 
 # The containing directory must be owned by the user who eventually runs rm.
 chown $NON_ROOT_USERNAME .
 
-mkdir a || framework_failure=1
-chmod 1777 a || framework_failure=1
-touch a/b || framework_failure=1
-
-if test $framework_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  (exit 1); exit 1
-fi
+mkdir a || framework_failure
+chmod 1777 a || framework_failure
+touch a/b || framework_failure
 
 fail=0
 
 # Try to ensure that $NON_ROOT_USERNAME can access
 # the required version of rm.
-rm_version=`setuidgid $NON_ROOT_USERNAME rm --version|sed -n '1s/.* //p'`
+rm_version=`setuidgid $NON_ROOT_USERNAME env PATH="$PATH" rm --version|sed -n '1s/.* //p'`
 case $rm_version in
   $PACKAGE_VERSION) ;;
-  *) echo "$0: cannot access required version ($PACKAGE_VERSION) of rm" 1>&2
+  *) echo "$0: cannot access just-built rm as user $NON_ROOT_USERNAME" 1>&2
      fail=1 ;;
 esac
-setuidgid $NON_ROOT_USERNAME rm -rf a 2> out-t && fail=1
+setuidgid $NON_ROOT_USERNAME env PATH="$PATH" rm -rf a 2> out-t && fail=1
 
 # On some systems, we get `Not owner'.  Convert it.
 # On other systems (HPUX), we get `Permission denied'.  Convert it, too.
@@ -69,7 +54,6 @@ cat <<\EOF > exp
 rm: cannot remove `a/b': Operation not permitted
 EOF
 
-cmp out exp || fail=1
-test $fail = 1 && diff out exp 2> /dev/null
+compare out exp || fail=1
 
 (exit $fail); exit $fail
diff --git a/tests/rm/fail-eacces b/tests/rm/fail-eacces
--- a/tests/rm/fail-eacces
+++ b/tests/rm/fail-eacces
@@ -1,11 +1,14 @@
 #!/bin/sh
 # Ensure that rm -rf unremovable-non-dir gives a diagnostic.
+# Test both a regular file and a symlink -- it makes a difference to rm.
+# With the symlink, rm from coreutils-6.9 would fail with a misleading
+# ELOOP diagnostic.
 
 # Copyright (C) 2006-2007 Free Software Foundation, Inc.
 
-# This program is free software; you can redistribute it and/or modify
+# This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 
 # This program is distributed in the hope that it will be useful,
@@ -14,9 +17,7 @@
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
-# 02110-1301, USA.
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 if test "$VERBOSE" = yes; then
   set -x
@@ -24,22 +25,22 @@ if test "$VERBOSE" = yes; then
 fi
 
 . $srcdir/../lang-default
-PRIV_CHECK_ARG=require-non-root . $srcdir/../priv-check
+. $srcdir/../test-lib.sh
+skip_if_root_
 
-pwd=`pwd`
-t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
-trap '(exit $?); exit $?' 1 2 13 15
+ok=0
+mkdir d           &&
+  touch d/f       &&
+  ln -s f d/slink &&
+  chmod a-w d     &&
+  ok=1
+test $ok = 1 || framework_failure
 
-framework_failure=0
-mkdir -p $tmp || framework_failure=1
-cd $tmp || framework_failure=1
-mkdir d && touch d/f && chmod a-w d || framework_failure=1
-
-if test $framework_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  (exit 1); exit 1
-fi
+mkdir e           &&
+  ln -s f e/slink &&
+  chmod a-w e     &&
+  ok=1
+test $ok = 1 || framework_failure
 
 fail=0
 
@@ -47,8 +48,13 @@ rm -rf d/f 2> out && fail=1
 cat <<\EOF > exp
 rm: cannot remove `d/f': Permission denied
 EOF
+compare out exp || fail=1
 
-cmp out exp || fail=1
-test $fail = 1 && diff out exp 2> /dev/null
+# This used to fail with ELOOP.
+rm -rf e 2> out && fail=1
+cat <<\EOF > exp
+rm: cannot remove `e/slink': Permission denied
+EOF
+compare out exp || fail=1
 
 (exit $fail); exit $fail
diff --git a/tests/rmdir/ignore b/tests/rmdir/ignore
--- a/tests/rmdir/ignore
+++ b/tests/rmdir/ignore
@@ -1,11 +1,11 @@
 #!/bin/sh
 # make sure rmdir's --ignore-fail-on-non-empty option works
 
-# Copyright (C) 1999 Free Software Foundation, Inc.
+# Copyright (C) 1999, 2007 Free Software Foundation, Inc.
 
-# This program is free software; you can redistribute it and/or modify
+# This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 
 # This program is distributed in the hope that it will be useful,
@@ -14,32 +14,24 @@
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
-# 02110-1301, USA.
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 if test "$VERBOSE" = yes; then
   set -x
   rmdir --version
 fi
 
-tmp=rmdir.$$
-trap "rm -rf $tmp" 0 1 2 3 15
+. $srcdir/../test-lib.sh
 
-test_failure=0
-mkdir -p $tmp/a/b $tmp/x || test_failure=1
-
-if test $test_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  exit 1
-fi
+cwd=`pwd`
+mkdir -p "$cwd/a/b/c" "$cwd/a/x" || framework_failure
 
 fail=0
-rmdir -p --ignore-fail-on-non-empty $tmp/a/b || fail=1
-# $tmp/x should remain
-test -d $tmp/x || fail=1
-# $tmp/{a,b} should be gone
-test -d $tmp/a && fail=1
-test -d $tmp/a/b && fail=1
+rmdir -p --ignore-fail-on-non-empty "$cwd/a/b/c" || fail=1
+# $cwd/a/x should remain
+test -d "$cwd/a/x" || fail=1
+# $cwd/a/b and $cwd/a/b/c should be gone
+test -d "$cwd/a/b" && fail=1
+test -d "$cwd/a/b/c" && fail=1
 
 exit $fail
diff --git a/tests/sample-test b/tests/sample-test
--- a/tests/sample-test
+++ b/tests/sample-test
@@ -1,11 +1,11 @@
 #!/bin/sh
 # FIXME
 
-# Copyright (C) 2007 Free Software Foundation, Inc.
+# Copyright (C) 2008 Free Software Foundation, Inc.
 
-# This program is free software; you can redistribute it and/or modify
+# This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 
 # This program is distributed in the hope that it will be useful,
@@ -14,9 +14,7 @@
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
-# 02110-1301, USA.
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 if test "$VERBOSE" = yes; then
   set -x
@@ -26,30 +24,19 @@ fi
 # FIXME: . $srcdir/../envvar-check
 # FIXME: . $srcdir/../lang-default
 # FIXME: PRIV_CHECK_ARG=require-root . $srcdir/../priv-check
-# FIXME: PRIV_CHECK_ARG=require-non-root . $srcdir/../priv-check
+. $srcdir/../test-lib.sh
+# FIXME skip_if_root_
 
-pwd=`pwd`
-t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
-trap '(exit $?); exit $?' 1 2 13 15
-
-framework_failure=0
-mkdir -p $tmp || framework_failure=1
-cd $tmp || framework_failure=1
-
-if test $framework_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  (exit 1); exit 1
-fi
+# If used, these must *follow* test-lib.sh.
+# FIXME: cleanup_() { rm -rf "$other_partition_tmpdir"; }
+# FIXME: . "$abs_top_srcdir/tests/other-fs-tmpdir"
 
 fail=0
-
 FIXME > out || fail=1
 cat <<\EOF > exp || fail=1
 FIXME
 EOF
 
-cmp out exp || fail=1
-test $fail = 1 && diff out exp 2> /dev/null
+compare out exp || fail=1
 
 (exit $fail); exit $fail
diff --git a/tests/sort/sort-tests b/tests/sort/sort-tests
--- a/tests/sort/sort-tests
+++ b/tests/sort/sort-tests
@@ -2214,8 +2214,44 @@ else
   esac
 fi
 test -s bigfield.E || rm -f bigfield.E
+_POSIX2_VERSION=199209 $xx +1x $srcdir/obs-inval.I > obs-inval.O 2> obs-inval.E
+code=$?
+if test $code != 2; then
+  $echo "Test obs-inval(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 2" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp obs-inval.O $srcdir/obs-inval.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed obs-inval(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test obs-inval(_POSIX2_VERSION=199209) failed: files obs-inval.O and $srcdir/obs-inval.X differ" 1>&2
+       (diff -c obs-inval.O $srcdir/obs-inval.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test obs-inval(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp obs-inval.O $srcdir/obs-inval.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s obs-inval.E || rm -f obs-inval.E
+_POSIX2_VERSION=199209 $xx -S1 $srcdir/realloc-buf.I > realloc-buf.O 2> realloc-buf.E
+code=$?
+if test $code != 0; then
+  $echo "Test realloc-buf(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp realloc-buf.O $srcdir/realloc-buf.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed realloc-buf(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test realloc-buf(_POSIX2_VERSION=199209) failed: files realloc-buf.O and $srcdir/realloc-buf.X differ" 1>&2
+       (diff -c realloc-buf.O $srcdir/realloc-buf.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test realloc-buf(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp realloc-buf.O $srcdir/realloc-buf.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s realloc-buf.E || rm -f realloc-buf.E
 if test $errors = 0; then
-  $echo Passed all 122 tests. 1>&2
+  $echo Passed all 124 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
diff --git a/tests/tr/tr-tests b/tests/tr/tr-tests
--- a/tests/tr/tr-tests
+++ b/tests/tr/tr-tests
@@ -2358,8 +2358,224 @@ else
   esac
 fi
 test -s fowler-1.E || rm -f fowler-1.E
+cat $srcdir/no-abort-1.I | $xx -c a '[b*256]' > no-abort-1.O 2> no-abort-1.E
+code=$?
+if test $code != 0; then
+  $echo "Test no-abort-1(|) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp no-abort-1.O $srcdir/no-abort-1.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed no-abort-1(|)"; fi;;
+    1) $echo "Test no-abort-1(|) failed: files no-abort-1.O and $srcdir/no-abort-1.X differ" 1>&2
+       (diff -c no-abort-1.O $srcdir/no-abort-1.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test no-abort-1(|) may have failed." 1>&2
+       $echo The command "cmp no-abort-1.O $srcdir/no-abort-1.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s no-abort-1.E || rm -f no-abort-1.E
+$xx -c a '[b*256]' < $srcdir/no-abort-1.I > no-abort-1.O 2> no-abort-1.E
+code=$?
+if test $code != 0; then
+  $echo "Test no-abort-1(<) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp no-abort-1.O $srcdir/no-abort-1.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed no-abort-1(<)"; fi;;
+    1) $echo "Test no-abort-1(<) failed: files no-abort-1.O and $srcdir/no-abort-1.X differ" 1>&2
+       (diff -c no-abort-1.O $srcdir/no-abort-1.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test no-abort-1(<) may have failed." 1>&2
+       $echo The command "cmp no-abort-1.O $srcdir/no-abort-1.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s no-abort-1.E || rm -f no-abort-1.E
+cat $srcdir/s1-lower.I | $xx '[:lower:]' '[.*]' > s1-lower.O 2> s1-lower.E
+code=$?
+if test $code != 0; then
+  $echo "Test s1-lower(|) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp s1-lower.O $srcdir/s1-lower.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed s1-lower(|)"; fi;;
+    1) $echo "Test s1-lower(|) failed: files s1-lower.O and $srcdir/s1-lower.X differ" 1>&2
+       (diff -c s1-lower.O $srcdir/s1-lower.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test s1-lower(|) may have failed." 1>&2
+       $echo The command "cmp s1-lower.O $srcdir/s1-lower.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s s1-lower.E || rm -f s1-lower.E
+$xx '[:lower:]' '[.*]' < $srcdir/s1-lower.I > s1-lower.O 2> s1-lower.E
+code=$?
+if test $code != 0; then
+  $echo "Test s1-lower(<) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp s1-lower.O $srcdir/s1-lower.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed s1-lower(<)"; fi;;
+    1) $echo "Test s1-lower(<) failed: files s1-lower.O and $srcdir/s1-lower.X differ" 1>&2
+       (diff -c s1-lower.O $srcdir/s1-lower.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test s1-lower(<) may have failed." 1>&2
+       $echo The command "cmp s1-lower.O $srcdir/s1-lower.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s s1-lower.E || rm -f s1-lower.E
+cat $srcdir/s1-upper.I | $xx '[:upper:]' '[.*]' > s1-upper.O 2> s1-upper.E
+code=$?
+if test $code != 0; then
+  $echo "Test s1-upper(|) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp s1-upper.O $srcdir/s1-upper.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed s1-upper(|)"; fi;;
+    1) $echo "Test s1-upper(|) failed: files s1-upper.O and $srcdir/s1-upper.X differ" 1>&2
+       (diff -c s1-upper.O $srcdir/s1-upper.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test s1-upper(|) may have failed." 1>&2
+       $echo The command "cmp s1-upper.O $srcdir/s1-upper.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s s1-upper.E || rm -f s1-upper.E
+$xx '[:upper:]' '[.*]' < $srcdir/s1-upper.I > s1-upper.O 2> s1-upper.E
+code=$?
+if test $code != 0; then
+  $echo "Test s1-upper(<) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp s1-upper.O $srcdir/s1-upper.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed s1-upper(<)"; fi;;
+    1) $echo "Test s1-upper(<) failed: files s1-upper.O and $srcdir/s1-upper.X differ" 1>&2
+       (diff -c s1-upper.O $srcdir/s1-upper.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test s1-upper(<) may have failed." 1>&2
+       $echo The command "cmp s1-upper.O $srcdir/s1-upper.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s s1-upper.E || rm -f s1-upper.E
+cat $srcdir/tolower-F.I | LC_CTYPE=en_US.ISO-8859-1 $xx '[:upper:]' '[:lower:]' > tolower-F.O 2> tolower-F.E
+code=$?
+if test $code != 0; then
+  $echo "Test tolower-F(LC_CTYPE=en_US.ISO-8859-1:|) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp tolower-F.O $srcdir/tolower-F.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed tolower-F(LC_CTYPE=en_US.ISO-8859-1:|)"; fi;;
+    1) $echo "Test tolower-F(LC_CTYPE=en_US.ISO-8859-1:|) failed: files tolower-F.O and $srcdir/tolower-F.X differ" 1>&2
+       (diff -c tolower-F.O $srcdir/tolower-F.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test tolower-F(LC_CTYPE=en_US.ISO-8859-1:|) may have failed." 1>&2
+       $echo The command "cmp tolower-F.O $srcdir/tolower-F.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s tolower-F.E || rm -f tolower-F.E
+LC_CTYPE=en_US.ISO-8859-1 $xx '[:upper:]' '[:lower:]' < $srcdir/tolower-F.I > tolower-F.O 2> tolower-F.E
+code=$?
+if test $code != 0; then
+  $echo "Test tolower-F(LC_CTYPE=en_US.ISO-8859-1:<) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp tolower-F.O $srcdir/tolower-F.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed tolower-F(LC_CTYPE=en_US.ISO-8859-1:<)"; fi;;
+    1) $echo "Test tolower-F(LC_CTYPE=en_US.ISO-8859-1:<) failed: files tolower-F.O and $srcdir/tolower-F.X differ" 1>&2
+       (diff -c tolower-F.O $srcdir/tolower-F.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test tolower-F(LC_CTYPE=en_US.ISO-8859-1:<) may have failed." 1>&2
+       $echo The command "cmp tolower-F.O $srcdir/tolower-F.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s tolower-F.E || rm -f tolower-F.E
+cat $srcdir/upcase-xtra.I | $xx '[:lower:].' '[:upper:]x' > upcase-xtra.O 2> upcase-xtra.E
+code=$?
+if test $code != 0; then
+  $echo "Test upcase-xtra(|) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp upcase-xtra.O $srcdir/upcase-xtra.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed upcase-xtra(|)"; fi;;
+    1) $echo "Test upcase-xtra(|) failed: files upcase-xtra.O and $srcdir/upcase-xtra.X differ" 1>&2
+       (diff -c upcase-xtra.O $srcdir/upcase-xtra.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test upcase-xtra(|) may have failed." 1>&2
+       $echo The command "cmp upcase-xtra.O $srcdir/upcase-xtra.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s upcase-xtra.E || rm -f upcase-xtra.E
+$xx '[:lower:].' '[:upper:]x' < $srcdir/upcase-xtra.I > upcase-xtra.O 2> upcase-xtra.E
+code=$?
+if test $code != 0; then
+  $echo "Test upcase-xtra(<) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp upcase-xtra.O $srcdir/upcase-xtra.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed upcase-xtra(<)"; fi;;
+    1) $echo "Test upcase-xtra(<) failed: files upcase-xtra.O and $srcdir/upcase-xtra.X differ" 1>&2
+       (diff -c upcase-xtra.O $srcdir/upcase-xtra.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test upcase-xtra(<) may have failed." 1>&2
+       $echo The command "cmp upcase-xtra.O $srcdir/upcase-xtra.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s upcase-xtra.E || rm -f upcase-xtra.E
+cat $srcdir/dncase-xtra.I | $xx '[:upper:].' '[:lower:]x' > dncase-xtra.O 2> dncase-xtra.E
+code=$?
+if test $code != 0; then
+  $echo "Test dncase-xtra(|) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp dncase-xtra.O $srcdir/dncase-xtra.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed dncase-xtra(|)"; fi;;
+    1) $echo "Test dncase-xtra(|) failed: files dncase-xtra.O and $srcdir/dncase-xtra.X differ" 1>&2
+       (diff -c dncase-xtra.O $srcdir/dncase-xtra.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test dncase-xtra(|) may have failed." 1>&2
+       $echo The command "cmp dncase-xtra.O $srcdir/dncase-xtra.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s dncase-xtra.E || rm -f dncase-xtra.E
+$xx '[:upper:].' '[:lower:]x' < $srcdir/dncase-xtra.I > dncase-xtra.O 2> dncase-xtra.E
+code=$?
+if test $code != 0; then
+  $echo "Test dncase-xtra(<) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp dncase-xtra.O $srcdir/dncase-xtra.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed dncase-xtra(<)"; fi;;
+    1) $echo "Test dncase-xtra(<) failed: files dncase-xtra.O and $srcdir/dncase-xtra.X differ" 1>&2
+       (diff -c dncase-xtra.O $srcdir/dncase-xtra.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test dncase-xtra(<) may have failed." 1>&2
+       $echo The command "cmp dncase-xtra.O $srcdir/dncase-xtra.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s dncase-xtra.E || rm -f dncase-xtra.E
 if test $errors = 0; then
-  $echo Passed all 130 tests. 1>&2
+  $echo Passed all 142 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
