Snapshot from coreutils-8.11.tar.xz

diff --git a/tests/cp/sparse-fiemap b/tests/cp/sparse-fiemap
--- a/tests/cp/sparse-fiemap
+++ b/tests/cp/sparse-fiemap
@@ -18,9 +18,13 @@
 
 . "${srcdir=.}/init.sh"; path_prepend_ ../src
 print_ver_ cp
+$PERL -e 1 || skip_test_ 'you lack perl'
 
-if fiemap_capable_ . ; then
-  : # Current dir is on a partition with working extents.  Good!
+# The test was seen to fail on ext3 so exclude that type
+# (or any file system where the type can't be determined)
+touch fiemap_chk
+if fiemap_capable_ fiemap_chk && ! df -t ext3 . >/dev/null; then
+  : # Current partition has working extents.  Good!
 else
   # It's not;  we need to create one, hence we need root access.
   require_root_
@@ -49,8 +53,6 @@ fi
 # in which it calls ioctl (fd, FS_IOC_FIEMAP,...
 # This also verifies that non-trivial extents are preserved.
 
-$PERL -e 1 || skip_test_ 'skipping part of this test; you lack perl'
-
 # Extract logical block number and length pairs from filefrag -v output.
 # The initial sed is to remove the "eof" from the normally-empty "flags" field.
 # Similarly, remove flags values like "unknown,delalloc,eof".
@@ -66,39 +68,41 @@ for i in $(seq 1 2 21); do
     $PERL -e 'BEGIN { $n = '$i' * 1024; *F = *STDOUT }' \
           -e 'for (1..'$j') { sysseek (*F, $n, 1)' \
           -e '&& syswrite (*F, chr($_)x$n) or die "$!"}' > j1 || fail=1
-    # sync
+
+    # Note there is an implicit sync performed by cp on Linux kernels
+    # before 2.6.39 to work around bugs in EXT4 and BTRFS.
+    # Note also the -s parameter to the filefrag commands below
+    # for the same reasons.
     cp --sparse=always j1 j2 || fail=1
-    # sync
-    # Technically we may need the 'sync' uses above, but
-    # uncommenting them makes this test take much longer.
 
     cmp j1 j2 || fail=1
-    filefrag -v j1 | grep extent \
-      || skip_test_ 'skipping part of this test; you lack filefrag'
+    if ! filefrag -vs j1 | grep -F extent >/dev/null; then
+      test $skip != 1 && warn_ 'skipping part; you lack filefrag'
+      skip=1
+    else
+      # Here is sample filefrag output:
+      #   $ perl -e 'BEGIN{$n=16*1024; *F=*STDOUT}' \
+      #          -e 'for (1..5) { sysseek(*F,$n,1)' \
+      #          -e '&& syswrite *F,"."x$n or die "$!"}' > j
+      #   $ filefrag -v j
+      #   File system type is: ef53
+      #   File size of j is 163840 (40 blocks, blocksize 4096)
+      #    ext logical physical expected length flags
+      #      0       4  6258884               4
+      #      1      12  6258892  6258887      4
+      #      2      20  6258900  6258895      4
+      #      3      28  6258908  6258903      4
+      #      4      36  6258916  6258911      4 eof
+      #   j: 6 extents found
 
-    # Here is sample filefrag output:
-    #   $ perl -e 'BEGIN{$n=16*1024; *F=*STDOUT}' \
-    #          -e 'for (1..5) { sysseek(*F,$n,1)' \
-    #          -e '&& syswrite *F,"."x$n or die "$!"}' > j
-    #   $ filefrag -v j
-    #   File system type is: ef53
-    #   File size of j is 163840 (40 blocks, blocksize 4096)
-    #    ext logical physical expected length flags
-    #      0       4  6258884               4
-    #      1      12  6258892  6258887      4
-    #      2      20  6258900  6258895      4
-    #      3      28  6258908  6258903      4
-    #      4      36  6258916  6258911      4 eof
-    #   j: 6 extents found
-
-    # exclude the physical block numbers; they always differ
-    filefrag -v j1 > ff1 || fail=1
-    filefrag -v j2 > ff2 || fail=1
-    { f ff1; f ff2; } \
-      | $PERL $abs_top_srcdir/tests/filefrag-extent-compare \
-        || { fail=1; break; }
+      # exclude the physical block numbers; they always differ
+      filefrag -v j1 > ff1 || framework_failure
+      filefrag -vs j2 > ff2 || framework_failure
+      { f ff1; f ff2; } | $PERL $abs_top_srcdir/tests/filefrag-extent-compare ||
+        fail=1
+    fi
+    test $fail = 1 && break 2
   done
-  test $fail = 1 && break
 done
 
 Exit $fail
