Snapshot from coreutils-7.1.tar.xz

diff --git a/tests/misc/help-version b/tests/misc/help-version
--- a/tests/misc/help-version
+++ b/tests/misc/help-version
@@ -28,6 +28,7 @@ export SHELL
 . $srcdir/test-lib.sh
 
 expected_failure_status_nohup=127
+expected_failure_status_timeout=125
 expected_failure_status_printenv=2
 expected_failure_status_tty=3
 expected_failure_status_sort=2
@@ -40,7 +41,7 @@ expected_failure_status_vdir=2
 fail=0
 
 test "$built_programs" \
-  || { echo "$this_test: no programs built!?!" 1>&2; (exit $fail); exit $fail; }
+  || { echo "$this_test: no programs built!?!" 1>&2; Exit $fail; }
 
 for lang in C fr da; do
   for i in $built_programs; do
@@ -50,8 +51,8 @@ for lang in C fr da; do
 
     # false fails even when invoked with --help or --version.
     if test $i = false; then
-      env LC_MESSAGES=$lang $i" --help >/dev/null && fail=1
-      env LC_MESSAGES=$lang $i" --version >/dev/null && fail=1
+      env LC_MESSAGES=$lang $i --help >/dev/null && fail=1
+      env LC_MESSAGES=$lang $i --version >/dev/null && fail=1
       continue
     fi
 
@@ -130,6 +131,7 @@ rmdir_args=$tmp_dir
 rm_args=$tmp_in
 shred_args=$tmp_in
 touch_args=$tmp_in2
+truncate_args="--reference=$tmp_in $tmp_in2"
 
 basename_args=$tmp_in
 dirname_args=$tmp_in
@@ -146,6 +148,7 @@ printf_args=foo
 seq_args=10
 sleep_args=0
 su_args=--version
+timeout_args=--version
 
 # I'd rather not run sync, since it spins up disks that I've
 # deliberately caused to spin down (but not unmounted).
@@ -160,7 +163,8 @@ df_args=/
 # This is necessary in the unusual event that getpwuid (getuid ()) fails.
 id_args=-u
 
-sleep 10m &
+# Use env to avoid invoking built-in sleep of Solaris 11's /bin/sh.
+env sleep 10m &
 kill_args=$!
 
 link_args="$tmp_in link-target"
@@ -195,4 +199,4 @@ for i in $built_programs; do
   rm -rf $tmp_in $tmp_in2 $tmp_out $tmp_dir
 done
 
-(exit $fail); exit $fail
+Exit $fail
diff --git a/tests/misc/printf-surprise b/tests/misc/printf-surprise
--- a/tests/misc/printf-surprise
+++ b/tests/misc/printf-surprise
@@ -54,6 +54,10 @@ fail=0
 
 mkfifo fifo || framework_failure
 
+# Disable MALLOC_PERTURB_, to avoid triggering this bug
+# http://bugs.debian.org/481543#77
+export MALLOC_PERTURB_=0
+
 head -c 10 fifo > out &
 ( ulimit -v 10000; env $prog %20000000f 0 2>err-msg > fifo )
 exit=$?
@@ -61,9 +65,14 @@ exit=$?
 # Map this longer, and rarer, diagnostic to the common one.
 # printf: cannot perform formatted output: Cannot allocate memory" \
 sed 's/cannot perform .*/write error/' err-msg > k && mv k err-msg
-err_msg=$(cat err-msg)
+err_msg=$(cat err-msg|tr '\n' :)
+
+# By some bug, on Solaris 11 (5.11 snv_86), err_msg ends up
+# containing '1> fifo:printf: write error:'.  Recognize that, too.
+
 case $err_msg in
-  "$prog: write error") diagnostic=y ;;
+  "$prog: write error:") diagnostic=y ;;
+  "1> fifo:$prog: write error:") diagnostic=y ;;
   '') diagnostic=n ;;
   *) diagnostic=unexpected ;;
 esac
@@ -73,13 +82,14 @@ case $n_out:$diagnostic:$exit in
   10:n:0) ;; # ok, succeeds w/no diagnostic: FreeBSD 6.1
   0:y:1)  ;; # ok, glibc-2.8 and newer, when printf(3) fails with ENOMEM
 
-  *:139)     # segfault; known bug at least in debian unstable's libc6 2.7-11
-     echo 1>&2 "$0: bug in snprintf causes low-mem use of printf to segfault"
-     fail=77;;
+  # With MALLOC_PERTURB_=0, this no longer happens.
+  # *:139)     # segfault; known bug at least in debian unstable's libc6 2.7-11
+  #    echo 1>&2 "$0: bug in snprintf causes low-mem use of printf to segfault"
+  #    fail=77;;
 
   # 10:y) ;; # Fail: doesn't happen: nobody succeeds with a diagnostic
   # 0:n)  ;; # Fail pre-patch: no output, no diag
   *) fail=1;;
 esac
 
-(exit $fail); exit $fail
+Exit $fail
