Snapshot from coreutils-6.12.tar.lzma

diff --git a/tests/misc/help-version b/tests/misc/help-version
--- a/tests/misc/help-version
+++ b/tests/misc/help-version
@@ -25,8 +25,7 @@ test "$VERBOSE" = yes && set -x
 test "x$SHELL" = x && SHELL=/bin/sh
 export SHELL
 
-. $srcdir/../envvar-check
-. $srcdir/../test-lib.sh
+. $srcdir/test-lib.sh
 
 expected_failure_status_nohup=127
 expected_failure_status_printenv=2
@@ -40,20 +39,19 @@ expected_failure_status_vdir=2
 
 fail=0
 
+test "$built_programs" \
+  || { echo "$this_test: no programs built!?!" 1>&2; (exit $fail); exit $fail; }
+
 for lang in C fr da; do
   for i in $built_programs; do
 
     # Skip `test'; it doesn't accept --help or --version.
     test $i = test && continue;
-    test $i = chcon && continue;
-    test $i = runcon && continue;
 
     # false fails even when invoked with --help or --version.
     if test $i = false; then
-      env LC_MESSAGES=$lang "$abs_top_builddir/src/$i" --help \
-	  >/dev/null && fail=1
-      env LC_MESSAGES=$lang "$abs_top_builddir/src/$i" --version \
-	  >/dev/null && fail=1
+      env LC_MESSAGES=$lang $i" --help >/dev/null && fail=1
+      env LC_MESSAGES=$lang $i" --version >/dev/null && fail=1
       continue
     fi
 
@@ -61,8 +59,8 @@ for lang in C fr da; do
     test $i = install && i=ginstall
 
     # Make sure they exit successfully, under normal conditions.
-    "$abs_top_builddir/src/$i" --help    > h-$i     || fail=1
-    "$abs_top_builddir/src/$i" --version >/dev/null || fail=1
+    env $i --help    > h-$i     || fail=1
+    env $i --version >/dev/null || fail=1
 
     # Make sure they mention the bug-reporting address in --help output.
     grep "$PACKAGE_BUGREPORT" h-$i > /dev/null || fail=1
@@ -70,8 +68,8 @@ for lang in C fr da; do
 
     # Make sure they fail upon `disk full' error.
     if test -w /dev/full && test -c /dev/full; then
-      "$abs_top_builddir/src/$i" --help    >/dev/full 2>/dev/null && fail=1
-      "$abs_top_builddir/src/$i" --version >/dev/full 2>/dev/null && fail=1
+      env $i --help    >/dev/full 2>/dev/null && fail=1
+      env $i --version >/dev/full 2>/dev/null && fail=1
       status=$?
       test $i = [ && prog=lbracket || prog=$i
       eval "expected=\$expected_failure_status_$prog"
@@ -188,7 +186,7 @@ for i in $built_programs; do
   # echo ================== $i
   test $i = [ && prog=lbracket || prog=$i
   eval "args=\$${prog}_args"
-  if "$abs_top_builddir/src/$i" $args < $tmp_in > $tmp_out; then
+  if env $i $args < $tmp_in > $tmp_out; then
     : # ok
   else
     echo FAIL: $i
