Snapshot from coreutils-8.8.tar.xz

diff --git a/tests/misc/printf-hex b/tests/misc/printf-hex
--- a/tests/misc/printf-hex
+++ b/tests/misc/printf-hex
@@ -16,18 +16,10 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-prog="$abs_top_builddir/src/printf"
+. "${srcdir=.}/init.sh"; path_prepend_ ../src
+print_ver_ printf
 
-if test "$VERBOSE" = yes; then
-  set -x
-  "$prog" --version
-fi
-
-. $srcdir/test-lib.sh
-
-
-
-"$prog" '\x7e3\n' > out || fail=1
+env printf '\x7e3\n' > out || fail=1
 cat <<\EOF > exp
 ~3
 EOF
