Snapshot from coreutils-6.11.tar.lzma

diff --git a/tests/join/join-tests b/tests/join/join-tests
--- a/tests/join/join-tests
+++ b/tests/join/join-tests
@@ -738,8 +738,134 @@ else
   esac
 fi
 test -s invalid-j.E || rm -f invalid-j.E
+$xx --check-order $srcdir/chkodr-1.I1 $srcdir/chkodr-1.I2 > chkodr-1.O 2> chkodr-1.E
+code=$?
+if test $code != 0; then
+  $echo "Test chkodr-1 failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp chkodr-1.O $srcdir/chkodr-1.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed chkodr-1"; fi;;
+    1) $echo "Test chkodr-1 failed: files chkodr-1.O and $srcdir/chkodr-1.X differ" 1>&2
+       (diff -c chkodr-1.O $srcdir/chkodr-1.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test chkodr-1 may have failed." 1>&2
+       $echo The command "cmp chkodr-1.O $srcdir/chkodr-1.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s chkodr-1.E || rm -f chkodr-1.E
+$xx --nocheck-order $srcdir/chkodr-2.I1 $srcdir/chkodr-2.I2 > chkodr-2.O 2> chkodr-2.E
+code=$?
+if test $code != 0; then
+  $echo "Test chkodr-2 failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp chkodr-2.O $srcdir/chkodr-2.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed chkodr-2"; fi;;
+    1) $echo "Test chkodr-2 failed: files chkodr-2.O and $srcdir/chkodr-2.X differ" 1>&2
+       (diff -c chkodr-2.O $srcdir/chkodr-2.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test chkodr-2 may have failed." 1>&2
+       $echo The command "cmp chkodr-2.O $srcdir/chkodr-2.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s chkodr-2.E || rm -f chkodr-2.E
+$xx --nocheck-order $srcdir/chkodr-3.I1 $srcdir/chkodr-3.I2 > chkodr-3.O 2> chkodr-3.E
+code=$?
+if test $code != 0; then
+  $echo "Test chkodr-3 failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp chkodr-3.O $srcdir/chkodr-3.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed chkodr-3"; fi;;
+    1) $echo "Test chkodr-3 failed: files chkodr-3.O and $srcdir/chkodr-3.X differ" 1>&2
+       (diff -c chkodr-3.O $srcdir/chkodr-3.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test chkodr-3 may have failed." 1>&2
+       $echo The command "cmp chkodr-3.O $srcdir/chkodr-3.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s chkodr-3.E || rm -f chkodr-3.E
+$xx  $srcdir/chkodr-4.I1 $srcdir/chkodr-4.I2 > chkodr-4.O 2> chkodr-4.E
+code=$?
+if test $code != 0; then
+  $echo "Test chkodr-4 failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp chkodr-4.O $srcdir/chkodr-4.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed chkodr-4"; fi;;
+    1) $echo "Test chkodr-4 failed: files chkodr-4.O and $srcdir/chkodr-4.X differ" 1>&2
+       (diff -c chkodr-4.O $srcdir/chkodr-4.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test chkodr-4 may have failed." 1>&2
+       $echo The command "cmp chkodr-4.O $srcdir/chkodr-4.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s chkodr-4.E || rm -f chkodr-4.E
+$xx --check-order $srcdir/chkodr-5.I1 $srcdir/chkodr-5.I2 > chkodr-5.O 2> chkodr-5.E
+code=$?
+if test $code != 1; then
+  $echo "Test chkodr-5 failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp chkodr-5.O $srcdir/chkodr-5.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed chkodr-5"; fi;;
+    1) $echo "Test chkodr-5 failed: files chkodr-5.O and $srcdir/chkodr-5.X differ" 1>&2
+       (diff -c chkodr-5.O $srcdir/chkodr-5.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test chkodr-5 may have failed." 1>&2
+       $echo The command "cmp chkodr-5.O $srcdir/chkodr-5.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s chkodr-5.E || rm -f chkodr-5.E
+$xx --nocheck-order $srcdir/chkodr-6.I1 $srcdir/chkodr-6.I2 > chkodr-6.O 2> chkodr-6.E
+code=$?
+if test $code != 0; then
+  $echo "Test chkodr-6 failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp chkodr-6.O $srcdir/chkodr-6.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed chkodr-6"; fi;;
+    1) $echo "Test chkodr-6 failed: files chkodr-6.O and $srcdir/chkodr-6.X differ" 1>&2
+       (diff -c chkodr-6.O $srcdir/chkodr-6.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test chkodr-6 may have failed." 1>&2
+       $echo The command "cmp chkodr-6.O $srcdir/chkodr-6.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s chkodr-6.E || rm -f chkodr-6.E
+$xx -12 $srcdir/chkodr-7.I1 $srcdir/chkodr-7.I2 > chkodr-7.O 2> chkodr-7.E
+code=$?
+if test $code != 0; then
+  $echo "Test chkodr-7 failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp chkodr-7.O $srcdir/chkodr-7.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed chkodr-7"; fi;;
+    1) $echo "Test chkodr-7 failed: files chkodr-7.O and $srcdir/chkodr-7.X differ" 1>&2
+       (diff -c chkodr-7.O $srcdir/chkodr-7.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test chkodr-7 may have failed." 1>&2
+       $echo The command "cmp chkodr-7.O $srcdir/chkodr-7.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s chkodr-7.E || rm -f chkodr-7.E
 if test $errors = 0; then
-  $echo Passed all 40 tests. 1>&2
+  $echo Passed all 47 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
diff --git a/tests/misc/ls-misc b/tests/misc/ls-misc
--- a/tests/misc/ls-misc
+++ b/tests/misc/ls-misc
@@ -1,7 +1,7 @@
 #!/bin/sh
 # -*- perl -*-
 
-# Copyright (C) 1998, 2000-2007 Free Software Foundation, Inc.
+# Copyright (C) 1998, 2000-2008 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,14 +16,8 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-: ${PERL=perl}
 : ${srcdir=.}
-
-$PERL -e 'use warnings;' > /dev/null 2>&1 || {
-  echo 1>&2 "$0: configure didn't find a usable version of Perl," \
-    "so can't run this test"
-  exit 77
-}
+. $srcdir/../require-perl
 
 me=`echo $0|sed 's,.*/,,'`
 exec $PERL -w -I$srcdir/.. -MCoreutils -M"CuTmpdir qw($me)" -- - << \EOF
@@ -34,6 +28,19 @@ use strict;
 
 # Turn off localisation of executable's ouput.
 @ENV{qw(LANGUAGE LANG LC_ALL)} = ('C') x 3;
+
+my $saved_ls_colors;
+
+sub push_ls_colors($)
+{
+  $saved_ls_colors = $ENV{LS_COLORS};
+  $ENV{LS_COLORS} = $_[0];
+}
+
+sub restore_ls_colors()
+{
+  $ENV{LS_COLORS} = $saved_ls_colors;
+}
 
 # If the string $S is a well-behaved file name, simply return it.
 # If it contains white space, quotes, etc., quote it, and return the new string.
@@ -52,17 +59,26 @@ sub shell_quote($)
 
 # Set up files used by the setuid-etc tests; skip this entire test if
 # that cannot be done.
-my $test = shell_quote "$ENV{abs_top_builddir}/src/test";
-system (qq(touch setuid && chmod u+s setuid && $test -u setuid &&
+sub setuid_setup()
+{
+  my $test = shell_quote "$ENV{abs_top_builddir}/src/test";
+  system (qq(touch setuid && chmod u+s setuid && $test -u setuid &&
 	   touch setgid && chmod g+s setgid && $test -g setgid &&
 	   mkdir sticky && chmod +t sticky  && $test -k sticky &&
 	   mkdir owt    && chmod +t,o+w owt && $test -k owt &&
 	   mkdir owr    && chmod o+w owr)) == 0
-  or (warn "$program_name: cannot create setuid/setgid/sticky files,"
-      . "so can't run this test\n"), exit 77;
+	     or (warn "$program_name: cannot create setuid/setgid/sticky files,"
+		 . "so can't run this test\n"), exit 77;
+}
 
-my $mkdir = {PRE => sub {mkdir 'd',0755 or die "d: $!\n"}};
-my $rmdir = {POST => sub {rmdir 'd' or die "d: $!\n"}};
+sub mkdir_d {mkdir 'd',0755 or die "d: $!\n"}
+sub rmdir_d {rmdir 'd'      or die "d: $!\n"}
+my $mkdir = {PRE => sub {mkdir_d}};
+my $rmdir = {POST => sub {rmdir_d}};
+my $mkdir_reg = {PRE => sub {mkdir_d; open (FH, '>d/f') && close FH
+			       or die "d/f: $!\n" }};
+my $rmdir_reg = {POST => sub {unlink 'd/f' or die "d/f: $!\n";
+			      rmdir 'd' or die "d: $!\n"}};
 
 my $mkdir2 = {PRE => sub {mkdir 'd',0755 or die "d: $!\n";
 			  mkdir 'd/e',0755 or die "d/e: $!\n" }};
@@ -72,14 +88,16 @@ my $rmdir2 = {POST => sub {rmdir 'd/e' or die "d/e: $!\n";
 my $target = {PRE => sub {
 		mkdir 'd',0755 or die "d: $!\n";
 		symlink '.', 'd/X' or die "d/X: $!\n";
-		$ENV{LS_COLORS}='ln=target'
+		push_ls_colors('ln=target')
 	      }};
 my $target2 = {POST => sub {unlink 'd/X' or die "d/X: $!\n";
-			    rmdir 'd' or die "d: $!\n" }};
+			    rmdir 'd' or die "d: $!\n";
+			    restore_ls_colors
+			    }};
 my $slink_d = {PRE => sub {symlink '/', 'd' or die "d: $!\n";
-                           $ENV{LS_COLORS}='ln=01;36:di=01;34:or=40;31;01'
+                           push_ls_colors('ln=01;36:di=01;34:or=40;31;01')
                            }};
-my $unlink_d = {POST => sub {unlink 'd' or die "d: $!\n"}};
+my $unlink_d = {POST => sub {unlink 'd' or die "d: $!\n"; restore_ls_colors}};
 
 my $mkdir_d_slink = {PRE => sub {mkdir 'd',0755 or die "d: $!\n";
 				 symlink '/', 'd/s' or die "d/s: $!\n" }};
@@ -93,9 +111,10 @@ sub make_j_d ()
   chmod 0555, 'j/d' or die "making j/d executable: $!\n";
 }
 
-my $exe_in_subdir = {PRE => sub { make_j_d (); $ENV{LS_COLORS}='ex=01;32' }};
+my $exe_in_subdir = {PRE => sub { make_j_d (); push_ls_colors('ex=01;32') }};
 my $remove_j = {POST => sub {unlink 'j/d' or die "j/d: $!\n";
-                             rmdir 'j' or die "j: $!\n" }};
+                             rmdir 'j' or die "j: $!\n";
+			     restore_ls_colors }};
 
 my $q_bell = {IN => {"q\a" => ''}};
 my @Tests =
@@ -138,6 +157,11 @@ my @Tests =
 				 {OUT => "\e[0m\e[01;36md\e[0m\@\n\e[m"},
 				  $slink_d, $unlink_d],
 
+     # A listing with no output should have no color sequences at all.
+     ['no-c-empty', '--color=always d', {OUT => ""}, $mkdir, $rmdir],
+     # A listing with only regular files should have no color sequences at all.
+     ['no-c-reg', '--color=always d', {OUT => "f\n"}, $mkdir_reg, $rmdir_reg],
+
      # Test for a bug fixed after coreutils-6.9.
      ['sl-target', '--color=always d',
       {OUT => "\e[0m\e[01;34mX\e[0m\n\e[m"}, $target, $target2],
@@ -149,10 +173,11 @@ my @Tests =
       {PRE => sub {
 		mkdir 'd',0755 or die "d: $!\n";
 		symlink 'non-existent', 'd/X' or die "d/X: $!\n";
-		$ENV{LS_COLORS}='or=40;31;01'
+		push_ls_colors('or=40;31;01')
 	      }},
       {POST => sub {unlink 'd/X' or die "d/X: $!\n";
-		    rmdir 'd' or die "d: $!\n" }},
+		    rmdir 'd' or die "d: $!\n";
+		    restore_ls_colors; }},
      ],
 
      # Test for a bug that was introduced in coreutils-4.5.4; fixed in 4.5.5.
@@ -190,10 +215,26 @@ my @Tests =
       $mkdir_d_slink, $rmdir_d_slink],
     );
 
+# Start with an unset LS_COLORS environment variable.
+delete $ENV{LS_COLORS};
+
 my $save_temps = $ENV{SAVE_TEMPS};
 my $verbose = $ENV{VERBOSE};
 
 my $prog = 'ls';
+
+setuid_setup;
 my $fail = run_tests ($program_name, $prog, \@Tests, $save_temps, $verbose);
+$fail
+  and exit 1;
+
+# Be careful to use the just-build dircolors.
+my $e = `$ENV{abs_top_builddir}/src/dircolors -b`;
+$e =~ s/^LS_COLORS=\'//;
+$e =~ s/\';.*//sm;
+$ENV{LS_COLORS} = $e;
+
+setuid_setup;
+$fail = run_tests ($program_name, $prog, \@Tests, $save_temps, $verbose);
 exit $fail;
 EOF
diff --git a/tests/pr/pr-tests b/tests/pr/pr-tests
--- a/tests/pr/pr-tests
+++ b/tests/pr/pr-tests
@@ -7146,8 +7146,80 @@ else
   esac
 fi
 test -s neg-page.E || rm -f neg-page.E
+$xx --date-format="-- Date/Time --" -h x -t -e $srcdir/neg-inp-pos1.I > neg-inp-pos1.O 2> neg-inp-pos1.E
+code=$?
+if test $code != 0; then
+  $echo "Test neg-inp-pos1 failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp neg-inp-pos1.O $srcdir/neg-inp-pos1.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed neg-inp-pos1"; fi;;
+    1) $echo "Test neg-inp-pos1 failed: files neg-inp-pos1.O and $srcdir/neg-inp-pos1.X differ" 1>&2
+       (diff -c neg-inp-pos1.O $srcdir/neg-inp-pos1.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test neg-inp-pos1 may have failed." 1>&2
+       $echo The command "cmp neg-inp-pos1.O $srcdir/neg-inp-pos1.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s neg-inp-pos1.E || rm -f neg-inp-pos1.E
+$xx --date-format="-- Date/Time --" -h x -t -e $srcdir/neg-inp-pos2.I > neg-inp-pos2.O 2> neg-inp-pos2.E
+code=$?
+if test $code != 0; then
+  $echo "Test neg-inp-pos2 failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp neg-inp-pos2.O $srcdir/neg-inp-pos2.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed neg-inp-pos2"; fi;;
+    1) $echo "Test neg-inp-pos2 failed: files neg-inp-pos2.O and $srcdir/neg-inp-pos2.X differ" 1>&2
+       (diff -c neg-inp-pos2.O $srcdir/neg-inp-pos2.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test neg-inp-pos2 may have failed." 1>&2
+       $echo The command "cmp neg-inp-pos2.O $srcdir/neg-inp-pos2.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s neg-inp-pos2.E || rm -f neg-inp-pos2.E
+$xx --date-format="-- Date/Time --" -h x -t -e300 $srcdir/smash-heap.I > smash-heap.O 2> smash-heap.E
+code=$?
+if test $code != 0; then
+  $echo "Test smash-heap failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp smash-heap.O $srcdir/smash-heap.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed smash-heap"; fi;;
+    1) $echo "Test smash-heap failed: files smash-heap.O and $srcdir/smash-heap.X differ" 1>&2
+       (diff -c smash-heap.O $srcdir/smash-heap.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test smash-heap may have failed." 1>&2
+       $echo The command "cmp smash-heap.O $srcdir/smash-heap.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s smash-heap.E || rm -f smash-heap.E
+$xx --date-format="-- Date/Time --" -h x -t -e $srcdir/smash-heap8.I > smash-heap8.O 2> smash-heap8.E
+code=$?
+if test $code != 0; then
+  $echo "Test smash-heap8 failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp smash-heap8.O $srcdir/smash-heap8.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed smash-heap8"; fi;;
+    1) $echo "Test smash-heap8 failed: files smash-heap8.O and $srcdir/smash-heap8.X differ" 1>&2
+       (diff -c smash-heap8.O $srcdir/smash-heap8.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test smash-heap8 may have failed." 1>&2
+       $echo The command "cmp smash-heap8.O $srcdir/smash-heap8.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s smash-heap8.E || rm -f smash-heap8.E
 if test $errors = 0; then
-  $echo Passed all 396 tests. 1>&2
+  $echo Passed all 400 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
diff --git a/tests/sort/sort-tests b/tests/sort/sort-tests
--- a/tests/sort/sort-tests
+++ b/tests/sort/sort-tests
@@ -2178,6 +2178,24 @@ else
   esac
 fi
 test -s incompat6.E || rm -f incompat6.E
+_POSIX2_VERSION=199209 $xx --sort=random -n $srcdir/incompat7.I > incompat7.O 2> incompat7.E
+code=$?
+if test $code != 2; then
+  $echo "Test incompat7(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 2" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp incompat7.O $srcdir/incompat7.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed incompat7(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test incompat7(_POSIX2_VERSION=199209) failed: files incompat7.O and $srcdir/incompat7.X differ" 1>&2
+       (diff -c incompat7.O $srcdir/incompat7.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test incompat7(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp incompat7.O $srcdir/incompat7.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s incompat7.E || rm -f incompat7.E
 _POSIX2_VERSION=199209 $xx -k2,2 -t '\0' $srcdir/nul-tab.I > nul-tab.O 2> nul-tab.E
 code=$?
 if test $code != 0; then
@@ -2250,8 +2268,44 @@ else
   esac
 fi
 test -s realloc-buf.E || rm -f realloc-buf.E
+_POSIX2_VERSION=199209 $xx --sort=numeric $srcdir/sort-numeric.I > sort-numeric.O 2> sort-numeric.E
+code=$?
+if test $code != 0; then
+  $echo "Test sort-numeric(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp sort-numeric.O $srcdir/sort-numeric.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed sort-numeric(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test sort-numeric(_POSIX2_VERSION=199209) failed: files sort-numeric.O and $srcdir/sort-numeric.X differ" 1>&2
+       (diff -c sort-numeric.O $srcdir/sort-numeric.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test sort-numeric(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp sort-numeric.O $srcdir/sort-numeric.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s sort-numeric.E || rm -f sort-numeric.E
+_POSIX2_VERSION=199209 $xx --sort=general-numeric $srcdir/sort-gennum.I > sort-gennum.O 2> sort-gennum.E
+code=$?
+if test $code != 0; then
+  $echo "Test sort-gennum(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp sort-gennum.O $srcdir/sort-gennum.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed sort-gennum(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test sort-gennum(_POSIX2_VERSION=199209) failed: files sort-gennum.O and $srcdir/sort-gennum.X differ" 1>&2
+       (diff -c sort-gennum.O $srcdir/sort-gennum.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test sort-gennum(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp sort-gennum.O $srcdir/sort-gennum.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s sort-gennum.E || rm -f sort-gennum.E
 if test $errors = 0; then
-  $echo Passed all 124 tests. 1>&2
+  $echo Passed all 127 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
