Snapshot from coreutils-6.6.tar.bz2

diff --git a/tests/ls/nameless-uid b/tests/ls/nameless-uid
--- a/tests/ls/nameless-uid
+++ b/tests/ls/nameless-uid
@@ -1,5 +1,5 @@
 #!/bin/sh
-# Demonstrate rm's new --one-file-system option.
+# Ensure that ls -l works on files with nameless uid and/or gid
 
 # Copyright (C) 2006 Free Software Foundation, Inc.
 
@@ -20,48 +20,46 @@
 
 if test "$VERBOSE" = yes; then
   set -x
-  rm --version
+  ls --version
 fi
 
-PRIV_CHECK_ARG=require-root . $srcdir/../priv-check
+. $srcdir/../envvar-check
 . $srcdir/../lang-default
-. $srcdir/../other-fs-tmpdir
+PRIV_CHECK_ARG=require-root . $srcdir/../priv-check
 
-if test -z "$other_partition_tmpdir"; then
+$PERL -e 1 > /dev/null 2>&1 || {
+  echo 1>&2 "$0: configure didn't find a usable version of Perl," \
+    "so can't run this test"
+  (exit 77); exit 77
+}
+
+nameless_uid=`$PERL -e 'foreach my $i (1000..16*1024) { getpwuid $i or (print "$i\n"), exit }'`
+
+if test x$nameless_uid = x; then
+  echo "$0: couldn't find a nameless UID" 1>&2
   (exit 77); exit 77
 fi
 
 pwd=`pwd`
 t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
+trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
 trap '(exit $?); exit $?' 1 2 13 15
-
-t0="$t0 $other_partition_tmpdir"
 
 framework_failure=0
 mkdir -p $tmp || framework_failure=1
 cd $tmp || framework_failure=1
 
-t=$other_partition_tmpdir
-mkdir -p a/b $t/y
-mount --bind $t a/b || framework_failure=1
-
-cat <<\EOF > exp || framework_failure=1
-rm: skipping `a/b', since it's on a different device
-EOF
+touch f || framework_failure=1
+chown $nameless_uid f || framework_failure=1
 
 if test $framework_failure = 1; then
-  echo "$0: setup failed; skipping this test" 1>&2
-  (exit 77); exit 77
+  echo "$0: failure in testing framework" 1>&2
+  (exit 1); exit 1
 fi
 
 fail=0
 
-rm --one-file-system -rf a 2> out && fail=1
-test -d $t/y || fail=1
-umount $t
-
-cmp out exp || fail=1
-test $fail = 1 && diff out exp 2> /dev/null
+set -- `ls -o f` || fail=1
+test $3 = $nameless_uid || fail=1
 
 (exit $fail); exit $fail
