Snapshot from coreutils-8.12.tar.xz

diff --git a/tests/tail-2/follow-name b/tests/tail-2/follow-name
--- a/tests/tail-2/follow-name
+++ b/tests/tail-2/follow-name
@@ -1,7 +1,7 @@
 #!/bin/sh
-# Ensure that "tail -f fifo" tails indefinitely.
+# ensure that --follow=name does not imply --retry
 
-# Copyright (C) 2009-2011 Free Software Foundation, Inc.
+# Copyright (C) 2011 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -19,14 +19,14 @@
 . "${srcdir=.}/init.sh"; path_prepend_ ../src
 print_ver_ tail
 
-mkfifo_or_skip_ fifo
+cat <<\EOF > exp || framework_failure_
+tail: cannot open `no-such' for reading: No such file or directory
+tail: no files remaining
+EOF
 
-echo 1 > fifo &
-echo 1 > exp || framework_failure
+timeout 10 tail --follow=name no-such > out 2> err
+test $? = 1 || fail=1
 
-timeout 10 tail -f fifo > out
-test $? = 124 || fail=1
-
-compare out exp || fail=1
+compare err exp || fail=1
 
 Exit $fail
