Snapshot from coreutils-6.9.tar.bz2

diff --git a/tests/install/basic-1 b/tests/install/basic-1
--- a/tests/install/basic-1
+++ b/tests/install/basic-1
@@ -1,8 +1,7 @@
 #! /bin/sh
 # Basic tests for "install".
 
-# Copyright (C) 1998, 2000, 2001, 2002, 2004, 2005, 2006 Free Software
-# Foundation, Inc.
+# Copyright (C) 1998, 2000-2002, 2004-2007 Free Software Foundation, Inc.
 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -130,13 +129,17 @@ test -d xx/rel && fail=1
 
 # Test that we can install from an unreadable directory with an
 # inaccessible parent.  coreutils 5.97 fails this test.
-mkdir -p sub1/d || fail=1
-(cd sub1/d && chmod a-rx .. && chmod a-r . &&
- ginstall -d "$abs/xx/zz" rel/a rel/b 2> /dev/null) || fail=1
-chmod 755 sub1 sub1/d || fail=1
-test -d xx/zz || fail=1
-test -d sub1/d/rel/a || fail=1
-test -d sub1/d/rel/b || fail=1
+# Perform this test only if "." is on a local file system.
+# Otherwise, it would fail e.g., on an NFS-mounted file system.
+if df --local . >/dev/null 2>&1; then
+  mkdir -p sub1/d || fail=1
+  (cd sub1/d && chmod a-r . && chmod a-rx .. &&
+   ginstall -d "$abs/xx/zz" rel/a rel/b) || fail=1
+  chmod 755 sub1 sub1/d || fail=1
+  test -d xx/zz || fail=1
+  test -d sub1/d/rel/a || fail=1
+  test -d sub1/d/rel/b || fail=1
+fi
 
 touch file || fail=1
 ginstall -Dv file sub3/a/b/c/file >out 2>&1 || fail=1
diff --git a/tests/join/join-tests b/tests/join/join-tests
--- a/tests/join/join-tests
+++ b/tests/join/join-tests
@@ -702,6 +702,24 @@ else
   esac
 fi
 test -s 8-bit-t.E || rm -f 8-bit-t.E
+$xx -1 340282366920938463463374607431768211456 -2 2 $srcdir/bigfield.I1 $srcdir/bigfield.I2 > bigfield.O 2> bigfield.E
+code=$?
+if test $code != 0; then
+  $echo "Test bigfield failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp bigfield.O $srcdir/bigfield.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed bigfield"; fi;;
+    1) $echo "Test bigfield failed: files bigfield.O and $srcdir/bigfield.X differ" 1>&2
+       (diff -c bigfield.O $srcdir/bigfield.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test bigfield may have failed." 1>&2
+       $echo The command "cmp bigfield.O $srcdir/bigfield.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s bigfield.E || rm -f bigfield.E
 $xx -j x  > invalid-j.O 2> invalid-j.E
 code=$?
 if test $code != 1; then
@@ -721,7 +739,7 @@ else
 fi
 test -s invalid-j.E || rm -f invalid-j.E
 if test $errors = 0; then
-  $echo Passed all 39 tests. 1>&2
+  $echo Passed all 40 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
diff --git a/tests/sort/sort-tests b/tests/sort/sort-tests
--- a/tests/sort/sort-tests
+++ b/tests/sort/sort-tests
@@ -360,6 +360,42 @@ else
   esac
 fi
 test -s 02c.E || rm -f 02c.E
+_POSIX2_VERSION=199209 $xx -C $srcdir/02d.I > 02d.O 2> 02d.E
+code=$?
+if test $code != 0; then
+  $echo "Test 02d(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp 02d.O $srcdir/02d.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed 02d(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test 02d(_POSIX2_VERSION=199209) failed: files 02d.O and $srcdir/02d.X differ" 1>&2
+       (diff -c 02d.O $srcdir/02d.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test 02d(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp 02d.O $srcdir/02d.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s 02d.E || rm -f 02d.E
+_POSIX2_VERSION=199209 $xx -C $srcdir/02e.I > 02e.O 2> 02e.E
+code=$?
+if test $code != 1; then
+  $echo "Test 02e(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 1" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp 02e.O $srcdir/02e.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed 02e(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test 02e(_POSIX2_VERSION=199209) failed: files 02e.O and $srcdir/02e.X differ" 1>&2
+       (diff -c 02e.O $srcdir/02e.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test 02e(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp 02e.O $srcdir/02e.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s 02e.E || rm -f 02e.E
 _POSIX2_VERSION=199209 $xx -cu $srcdir/02m.I > 02m.O 2> 02m.E
 code=$?
 if test $code != 1; then
@@ -2106,6 +2142,42 @@ else
   esac
 fi
 test -s incompat4.E || rm -f incompat4.E
+_POSIX2_VERSION=199209 $xx -C -o /dev/null $srcdir/incompat5.I > incompat5.O 2> incompat5.E
+code=$?
+if test $code != 2; then
+  $echo "Test incompat5(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 2" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp incompat5.O $srcdir/incompat5.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed incompat5(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test incompat5(_POSIX2_VERSION=199209) failed: files incompat5.O and $srcdir/incompat5.X differ" 1>&2
+       (diff -c incompat5.O $srcdir/incompat5.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test incompat5(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp incompat5.O $srcdir/incompat5.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s incompat5.E || rm -f incompat5.E
+_POSIX2_VERSION=199209 $xx -cC $srcdir/incompat6.I > incompat6.O 2> incompat6.E
+code=$?
+if test $code != 2; then
+  $echo "Test incompat6(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 2" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp incompat6.O $srcdir/incompat6.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed incompat6(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test incompat6(_POSIX2_VERSION=199209) failed: files incompat6.O and $srcdir/incompat6.X differ" 1>&2
+       (diff -c incompat6.O $srcdir/incompat6.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test incompat6(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp incompat6.O $srcdir/incompat6.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s incompat6.E || rm -f incompat6.E
 _POSIX2_VERSION=199209 $xx -k2,2 -t '\0' $srcdir/nul-tab.I > nul-tab.O 2> nul-tab.E
 code=$?
 if test $code != 0; then
@@ -2124,8 +2196,26 @@ else
   esac
 fi
 test -s nul-tab.E || rm -f nul-tab.E
+_POSIX2_VERSION=199209 $xx -k 340282366920938463463374607431768211456 $srcdir/bigfield.I > bigfield.O 2> bigfield.E
+code=$?
+if test $code != 0; then
+  $echo "Test bigfield(_POSIX2_VERSION=199209) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp bigfield.O $srcdir/bigfield.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed bigfield(_POSIX2_VERSION=199209)"; fi;;
+    1) $echo "Test bigfield(_POSIX2_VERSION=199209) failed: files bigfield.O and $srcdir/bigfield.X differ" 1>&2
+       (diff -c bigfield.O $srcdir/bigfield.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test bigfield(_POSIX2_VERSION=199209) may have failed." 1>&2
+       $echo The command "cmp bigfield.O $srcdir/bigfield.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s bigfield.E || rm -f bigfield.E
 if test $errors = 0; then
-  $echo Passed all 117 tests. 1>&2
+  $echo Passed all 122 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
diff --git a/tests/uniq/uniq-tests b/tests/uniq/uniq-tests
--- a/tests/uniq/uniq-tests
+++ b/tests/uniq/uniq-tests
@@ -1890,37 +1890,19 @@ else
   esac
 fi
 test -s 111.E || rm -f 111.E
-cat $srcdir/112.I | $xx -D -c > 112.O 2> 112.E
-code=$?
-if test $code != 1; then
-  $echo "Test 112(|) failed: $xx return code $code differs from expected value 1" 1>&2
-  errors=`expr $errors + 1`
-else
-  cmp 112.O $srcdir/112.X > /dev/null 2>&1
-  case $? in
-    0) if test "$VERBOSE"; then $echo "passed 112(|)"; fi;;
-    1) $echo "Test 112(|) failed: files 112.O and $srcdir/112.X differ" 1>&2
-       (diff -c 112.O $srcdir/112.X) 2> /dev/null
-       errors=`expr $errors + 1`;;
-    2) $echo "Test 112(|) may have failed." 1>&2
-       $echo The command "cmp 112.O $srcdir/112.X" failed. 1>&2
-       errors=`expr $errors + 1`;;
-  esac
-fi
-test -s 112.E || rm -f 112.E
 $xx -D -c < $srcdir/112.I > 112.O 2> 112.E
 code=$?
 if test $code != 1; then
-  $echo "Test 112(<) failed: $xx return code $code differs from expected value 1" 1>&2
+  $echo "Test 112 failed: $xx return code $code differs from expected value 1" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 112.O $srcdir/112.X > /dev/null 2>&1
   case $? in
-    0) if test "$VERBOSE"; then $echo "passed 112(<)"; fi;;
-    1) $echo "Test 112(<) failed: files 112.O and $srcdir/112.X differ" 1>&2
+    0) if test "$VERBOSE"; then $echo "passed 112"; fi;;
+    1) $echo "Test 112 failed: files 112.O and $srcdir/112.X differ" 1>&2
        (diff -c 112.O $srcdir/112.X) 2> /dev/null
        errors=`expr $errors + 1`;;
-    2) $echo "Test 112(<) may have failed." 1>&2
+    2) $echo "Test 112 may have failed." 1>&2
        $echo The command "cmp 112.O $srcdir/112.X" failed. 1>&2
        errors=`expr $errors + 1`;;
   esac
@@ -2196,8 +2178,44 @@ else
   esac
 fi
 test -s 120.E || rm -f 120.E
+cat $srcdir/121.I | $xx -d -u -w340282366920938463463374607431768211456 > 121.O 2> 121.E
+code=$?
+if test $code != 0; then
+  $echo "Test 121(|) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp 121.O $srcdir/121.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed 121(|)"; fi;;
+    1) $echo "Test 121(|) failed: files 121.O and $srcdir/121.X differ" 1>&2
+       (diff -c 121.O $srcdir/121.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test 121(|) may have failed." 1>&2
+       $echo The command "cmp 121.O $srcdir/121.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s 121.E || rm -f 121.E
+$xx -d -u -w340282366920938463463374607431768211456 < $srcdir/121.I > 121.O 2> 121.E
+code=$?
+if test $code != 0; then
+  $echo "Test 121(<) failed: $xx return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp 121.O $srcdir/121.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE"; then $echo "passed 121(<)"; fi;;
+    1) $echo "Test 121(<) failed: files 121.O and $srcdir/121.X differ" 1>&2
+       (diff -c 121.O $srcdir/121.X) 2> /dev/null
+       errors=`expr $errors + 1`;;
+    2) $echo "Test 121(<) may have failed." 1>&2
+       $echo The command "cmp 121.O $srcdir/121.X" failed. 1>&2
+       errors=`expr $errors + 1`;;
+  esac
+fi
+test -s 121.E || rm -f 121.E
 if test $errors = 0; then
-  $echo Passed all 121 tests. 1>&2
+  $echo Passed all 122 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
