Snapshot from coreutils-5.2.0.tar.bz2

diff --git a/tests/expr/basic b/tests/expr/basic
--- a/tests/expr/basic
+++ b/tests/expr/basic
@@ -4,13 +4,11 @@
 : ${PERL=perl}
 : ${srcdir=.}
 
-case "$PERL" in
-  *'missing perl')
-    echo 1>&2 "$0: configure didn't find a usable version of Perl," \
-      "so can't run this test"
-    exit 77
-    ;;
-esac
+$PERL -e 1 > /dev/null 2>&1 || {
+  echo 1>&2 "$0: configure didn't find a usable version of Perl," \
+    "so can't run this test"
+  exit 77
+}
 
 d=$srcdir/..
 exec $PERL -w -I$d -MFetish -- - << \EOF
@@ -46,6 +44,12 @@ my @Tests =
 
      # This erroneously succeeded and output `3' before 2.0.12.
      ['fail-a', '3 + -', {ERR => "$prog: non-numeric argument\n"},
+      {EXIT => 3}],
+
+     ['fail-b', '9 9', {ERR => "$prog: syntax error\n"},
+      {EXIT => 2}],
+     ['fail-c', {ERR => "$prog: too few arguments\n"
+		 . "Try `$prog --help' for more information.\n"},
       {EXIT => 2}],
     );
 
diff --git a/tests/fmt/basic b/tests/fmt/basic
--- a/tests/fmt/basic
+++ b/tests/fmt/basic
@@ -4,12 +4,11 @@
 : ${PERL=perl}
 : ${srcdir=.}
 
-case "$PERL" in
-  *'missing perl')
-  echo 1>&2 "$0: configure didn't find a usable version of Perl, so can't run this test"
+$PERL -e 1 > /dev/null 2>&1 || {
+  echo 1>&2 "$0: configure didn't find a usable version of Perl," \
+    "so can't run this test"
   exit 77
-  ;;
-esac
+}
 
 # Export this to avoid hassles when run in a UTF-8 locale,
 # since we use 8-bit characters below, and those values are
@@ -30,6 +29,15 @@ my @Tests =
       {OUT=>"ça b\n"}],
      ['wide-1', '-32768',	{IN=> "a\n"}, {OUT=>"a\n"}],
      ['wide-2', '-2147483647',	{IN=> "a\n"}, {OUT=>"a\n"}],
+     ['bad-suffix', '-72x',	{IN=> ''},
+      {ERR => "fmt: invalid width option: `-72x'\n"}, {EXIT => 1}],
+     ['no-file', 'no-such-file',
+      {ERR => "fmt: cannot open `no-such-file' for reading:"
+       . " No such file or directory\n"}, {EXIT => 1}],
+     ['obs-1', '-c -72',
+      {ERR => "fmt: invalid option -- 7; -WIDTH is recognized only when it"
+       . " is the first\noption; use -w N instead\n"
+       . "Try `fmt --help' for more information.\n" }, {EXIT => 1}],
     );
 
 my $save_temps = $ENV{DEBUG};
diff --git a/tests/rm/fail-2eperm b/tests/rm/fail-2eperm
--- a/tests/rm/fail-2eperm
+++ b/tests/rm/fail-2eperm
@@ -19,16 +19,8 @@ framework_failure=0
 mkdir -p $tmp || framework_failure=1
 cd $tmp || framework_failure=1
 
-# Find a username with UID != 0, and a valid shell.
-non_root_username=
-names=`grep -v '[^:]*:[^:]*:0:' /etc/passwd| sed 's/:.*//'`
-for name in $names; do
-  su -c ':' $name && { non_root_username=$name; break; }
-done
-test "x$non_root_username" = x && framework_failure=1
-
 # The containing directory must be owned by the user who eventually runs rm.
-chown $non_root_username .
+chown $NON_ROOT_USERNAME .
 
 mkdir a || framework_failure=1
 chmod 1777 a || framework_failure=1
@@ -41,7 +33,21 @@ fi
 
 fail=0
 
-su -c 'rm -rf a' $non_root_username 2> out && fail=1
+# Try to ensure that $NON_ROOT_USERNAME can access
+# the required version of rm.
+rm_version=`setuidgid $NON_ROOT_USERNAME rm --version|sed -n '1s/.* //p'`
+case $rm_version in
+  $PACKAGE_VERSION) ;;
+  *) echo "$0: cannot access required version ($PACKAGE_VERSION) of rm" 1>&2
+     fail=1 ;;
+esac
+setuidgid $NON_ROOT_USERNAME rm -rf a 2> out-t && fail=1
+
+# On some systems, we get `Not owner'.  Convert it.
+# On other systems (HPUX), we get `Permission denied'.  Convert it, too.
+onp='Operation not permitted'
+sed "s/Not owner/$onp/;s/Permission denied/$onp/" out-t > out
+
 cat <<\EOF > exp
 rm: cannot remove `a/b': Operation not permitted
 EOF
